/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import nz.co.blink.debit.dto.v1.BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The decoupled flow bank feature
 */
@JsonPropertyOrder({
  BankMetadataFeaturesDecoupledFlow.JSON_PROPERTY_ENABLED,
  BankMetadataFeaturesDecoupledFlow.JSON_PROPERTY_AVAILABLE_IDENTIFIERS,
  BankMetadataFeaturesDecoupledFlow.JSON_PROPERTY_REQUEST_TIMEOUT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BankMetadataFeaturesDecoupledFlow {
  public static final String JSON_PROPERTY_ENABLED = "enabled";
  
  private Boolean enabled;

  public static final String JSON_PROPERTY_AVAILABLE_IDENTIFIERS = "available_identifiers";
  
  private List<@Valid BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner> availableIdentifiers = new ArrayList<>();

  public static final String JSON_PROPERTY_REQUEST_TIMEOUT = "request_timeout";
  
  private String requestTimeout;

  public BankMetadataFeaturesDecoupledFlow() { 
  }

  public BankMetadataFeaturesDecoupledFlow enabled( Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Whether the Decoupled Flow is enabled.
   * @return enabled
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnabled( Boolean enabled) {
    this.enabled = enabled;
  }


  public BankMetadataFeaturesDecoupledFlow availableIdentifiers( List<@Valid BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner> availableIdentifiers) {
    this.availableIdentifiers = availableIdentifiers;
    return this;
  }

  public BankMetadataFeaturesDecoupledFlow addAvailableIdentifiersItem(BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner availableIdentifiersItem) {
    if (this.availableIdentifiers == null) {
      this.availableIdentifiers = new ArrayList<>();
    }
    this.availableIdentifiers.add(availableIdentifiersItem);
    return this;
  }

  /**
   * If enabled, will show the available fields to use to identify the customer with their bank.
   * @return availableIdentifiers
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_AVAILABLE_IDENTIFIERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner> getAvailableIdentifiers() {
    return availableIdentifiers;
  }


  @JsonProperty(value = JSON_PROPERTY_AVAILABLE_IDENTIFIERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailableIdentifiers( List<@Valid BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner> availableIdentifiers) {
    this.availableIdentifiers = availableIdentifiers;
  }


  public BankMetadataFeaturesDecoupledFlow requestTimeout( String requestTimeout) {
    this.requestTimeout = requestTimeout;
    return this;
  }

  /**
   * ISO8601 time duration until the decoupled flow consent request times out
   * @return requestTimeout
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_REQUEST_TIMEOUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRequestTimeout() {
    return requestTimeout;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_TIMEOUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestTimeout( String requestTimeout) {
    this.requestTimeout = requestTimeout;
  }


  /**
   * Return true if this bank_metadata_features_decoupled_flow object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankMetadataFeaturesDecoupledFlow bankMetadataFeaturesDecoupledFlow = (BankMetadataFeaturesDecoupledFlow) o;
    return Objects.equals(this.enabled, bankMetadataFeaturesDecoupledFlow.enabled) &&
        Objects.equals(this.availableIdentifiers, bankMetadataFeaturesDecoupledFlow.availableIdentifiers) &&
        Objects.equals(this.requestTimeout, bankMetadataFeaturesDecoupledFlow.requestTimeout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, availableIdentifiers, requestTimeout);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankMetadataFeaturesDecoupledFlow {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    availableIdentifiers: ").append(toIndentedString(availableIdentifiers)).append("\n");
    sb.append("    requestTimeout: ").append(toIndentedString(requestTimeout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `enabled` to the URL query string
    if (getEnabled() != null) {
      joiner.add(String.format(Locale.ROOT, "%senabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnabled()))));
    }

    // add `available_identifiers` to the URL query string
    if (getAvailableIdentifiers() != null) {
      for (int i = 0; i < getAvailableIdentifiers().size(); i++) {
        if (getAvailableIdentifiers().get(i) != null) {
          joiner.add(getAvailableIdentifiers().get(i).toUrlQueryString(String.format(Locale.ROOT, "%savailable_identifiers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `request_timeout` to the URL query string
    if (getRequestTimeout() != null) {
      joiner.add(String.format(Locale.ROOT, "%srequest_timeout%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestTimeout()))));
    }

    return joiner.toString();
  }
}

