/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The enduring consent bank feature
 */
@JsonPropertyOrder({
  BankMetadataFeaturesEnduringConsent.JSON_PROPERTY_ENABLED,
  BankMetadataFeaturesEnduringConsent.JSON_PROPERTY_MAXIMUM_CONSENT,
  BankMetadataFeaturesEnduringConsent.JSON_PROPERTY_CONSENT_INDEFINITE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BankMetadataFeaturesEnduringConsent {
  public static final String JSON_PROPERTY_ENABLED = "enabled";
  
  private Boolean enabled;

  public static final String JSON_PROPERTY_MAXIMUM_CONSENT = "maximum_consent";
  
  private String maximumConsent;

  public static final String JSON_PROPERTY_CONSENT_INDEFINITE = "consent_indefinite";
  
  private Boolean consentIndefinite;

  public BankMetadataFeaturesEnduringConsent() { 
  }

  public BankMetadataFeaturesEnduringConsent enabled( Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * If enduring consent is disabled, only single payment consents can be issued.
   * @return enabled
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnabled( Boolean enabled) {
    this.enabled = enabled;
  }


  public BankMetadataFeaturesEnduringConsent maximumConsent( String maximumConsent) {
    this.maximumConsent = maximumConsent;
    return this;
  }

  /**
   * ISO8601 time duration for the maximum allowed enduring consent period, i.e. how long the consent could be used to execute payments for. Appears only if consent_indefinite is false
   * @return maximumConsent
   */
  

  @JsonProperty(value = JSON_PROPERTY_MAXIMUM_CONSENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMaximumConsent() {
    return maximumConsent;
  }


  @JsonProperty(value = JSON_PROPERTY_MAXIMUM_CONSENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaximumConsent( String maximumConsent) {
    this.maximumConsent = maximumConsent;
  }


  public BankMetadataFeaturesEnduringConsent consentIndefinite( Boolean consentIndefinite) {
    this.consentIndefinite = consentIndefinite;
    return this;
  }

  /**
   * If the consenting period for payments is indefinite or time-limited by the bank
   * @return consentIndefinite
   */
  

  @JsonProperty(value = JSON_PROPERTY_CONSENT_INDEFINITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getConsentIndefinite() {
    return consentIndefinite;
  }


  @JsonProperty(value = JSON_PROPERTY_CONSENT_INDEFINITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConsentIndefinite( Boolean consentIndefinite) {
    this.consentIndefinite = consentIndefinite;
  }


  /**
   * Return true if this bank_metadata_features_enduring_consent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankMetadataFeaturesEnduringConsent bankMetadataFeaturesEnduringConsent = (BankMetadataFeaturesEnduringConsent) o;
    return Objects.equals(this.enabled, bankMetadataFeaturesEnduringConsent.enabled) &&
        Objects.equals(this.maximumConsent, bankMetadataFeaturesEnduringConsent.maximumConsent) &&
        Objects.equals(this.consentIndefinite, bankMetadataFeaturesEnduringConsent.consentIndefinite);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, maximumConsent, consentIndefinite);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankMetadataFeaturesEnduringConsent {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    maximumConsent: ").append(toIndentedString(maximumConsent)).append("\n");
    sb.append("    consentIndefinite: ").append(toIndentedString(consentIndefinite)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `enabled` to the URL query string
    if (getEnabled() != null) {
      joiner.add(String.format(Locale.ROOT, "%senabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnabled()))));
    }

    // add `maximum_consent` to the URL query string
    if (getMaximumConsent() != null) {
      joiner.add(String.format(Locale.ROOT, "%smaximum_consent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaximumConsent()))));
    }

    // add `consent_indefinite` to the URL query string
    if (getConsentIndefinite() != null) {
      joiner.add(String.format(Locale.ROOT, "%sconsent_indefinite%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConsentIndefinite()))));
    }

    return joiner.toString();
  }
}

