/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import nz.co.blink.debit.dto.v1.Amount;
import nz.co.blink.debit.dto.v1.Bank;
import nz.co.blink.debit.dto.v1.BankMetadataFeatures;
import nz.co.blink.debit.dto.v1.BankMetadataRedirectFlow;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * Information about a banks enabled features.
 */
@JsonPropertyOrder({
  BankMetadata.JSON_PROPERTY_NAME,
  BankMetadata.JSON_PROPERTY_PAYMENT_LIMIT,
  BankMetadata.JSON_PROPERTY_FEATURES,
  BankMetadata.JSON_PROPERTY_REDIRECT_FLOW
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BankMetadata {
  public static final String JSON_PROPERTY_NAME = "name";
  
  private Bank name;

  public static final String JSON_PROPERTY_PAYMENT_LIMIT = "payment_limit";
  
  private Amount paymentLimit;

  public static final String JSON_PROPERTY_FEATURES = "features";
  
  private BankMetadataFeatures features;

  public static final String JSON_PROPERTY_REDIRECT_FLOW = "redirect_flow";
  
  private BankMetadataRedirectFlow redirectFlow;

  public BankMetadata() { 
  }

  public BankMetadata name( Bank name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Bank getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName( Bank name) {
    this.name = name;
  }


  public BankMetadata paymentLimit( Amount paymentLimit) {
    this.paymentLimit = paymentLimit;
    return this;
  }

  /**
   * Get paymentLimit
   * @return paymentLimit
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PAYMENT_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Amount getPaymentLimit() {
    return paymentLimit;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentLimit( Amount paymentLimit) {
    this.paymentLimit = paymentLimit;
  }


  public BankMetadata features( BankMetadataFeatures features) {
    this.features = features;
    return this;
  }

  /**
   * Get features
   * @return features
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_FEATURES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BankMetadataFeatures getFeatures() {
    return features;
  }


  @JsonProperty(value = JSON_PROPERTY_FEATURES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFeatures( BankMetadataFeatures features) {
    this.features = features;
  }


  public BankMetadata redirectFlow( BankMetadataRedirectFlow redirectFlow) {
    this.redirectFlow = redirectFlow;
    return this;
  }

  /**
   * Get redirectFlow
   * @return redirectFlow
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_REDIRECT_FLOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BankMetadataRedirectFlow getRedirectFlow() {
    return redirectFlow;
  }


  @JsonProperty(value = JSON_PROPERTY_REDIRECT_FLOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedirectFlow( BankMetadataRedirectFlow redirectFlow) {
    this.redirectFlow = redirectFlow;
  }


  /**
   * Return true if this bank-metadata object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankMetadata bankMetadata = (BankMetadata) o;
    return Objects.equals(this.name, bankMetadata.name) &&
        Objects.equals(this.paymentLimit, bankMetadata.paymentLimit) &&
        Objects.equals(this.features, bankMetadata.features) &&
        Objects.equals(this.redirectFlow, bankMetadata.redirectFlow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, paymentLimit, features, redirectFlow);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankMetadata {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    paymentLimit: ").append(toIndentedString(paymentLimit)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    redirectFlow: ").append(toIndentedString(redirectFlow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `payment_limit` to the URL query string
    if (getPaymentLimit() != null) {
      joiner.add(getPaymentLimit().toUrlQueryString(prefix + "payment_limit" + suffix));
    }

    // add `features` to the URL query string
    if (getFeatures() != null) {
      joiner.add(getFeatures().toUrlQueryString(prefix + "features" + suffix));
    }

    // add `redirect_flow` to the URL query string
    if (getRedirectFlow() != null) {
      joiner.add(getRedirectFlow().toUrlQueryString(prefix + "redirect_flow" + suffix));
    }

    return joiner.toString();
  }
}

