/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * Details about the mandatory redirect flow functionality.
 */
@JsonPropertyOrder({
  BankMetadataRedirectFlow.JSON_PROPERTY_ENABLED,
  BankMetadataRedirectFlow.JSON_PROPERTY_REQUEST_TIMEOUT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BankMetadataRedirectFlow {
  public static final String JSON_PROPERTY_ENABLED = "enabled";
  
  private Boolean enabled;

  public static final String JSON_PROPERTY_REQUEST_TIMEOUT = "request_timeout";
  
  private String requestTimeout;

  public BankMetadataRedirectFlow() { 
  }

  public BankMetadataRedirectFlow enabled( Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Whether the redirect flow is enabled
   * @return enabled
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnabled( Boolean enabled) {
    this.enabled = enabled;
  }


  public BankMetadataRedirectFlow requestTimeout( String requestTimeout) {
    this.requestTimeout = requestTimeout;
    return this;
  }

  /**
   * ISO8601 time duration until the redirect flow consent request times out
   * @return requestTimeout
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_REQUEST_TIMEOUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRequestTimeout() {
    return requestTimeout;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_TIMEOUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestTimeout( String requestTimeout) {
    this.requestTimeout = requestTimeout;
  }


  /**
   * Return true if this bank_metadata_redirect_flow object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankMetadataRedirectFlow bankMetadataRedirectFlow = (BankMetadataRedirectFlow) o;
    return Objects.equals(this.enabled, bankMetadataRedirectFlow.enabled) &&
        Objects.equals(this.requestTimeout, bankMetadataRedirectFlow.requestTimeout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, requestTimeout);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankMetadataRedirectFlow {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    requestTimeout: ").append(toIndentedString(requestTimeout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `enabled` to the URL query string
    if (getEnabled() != null) {
      joiner.add(String.format(Locale.ROOT, "%senabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnabled()))));
    }

    // add `request_timeout` to the URL query string
    if (getRequestTimeout() != null) {
      joiner.add(String.format(Locale.ROOT, "%srequest_timeout%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestTimeout()))));
    }

    return joiner.toString();
  }
}

