/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import nz.co.blink.debit.dto.v1.IdentifierType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner
 */
@JsonPropertyOrder({
  BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner.JSON_PROPERTY_TYPE,
  BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner.JSON_PROPERTY_REGEX,
  BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner.JSON_PROPERTY_NAME,
  BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner.JSON_PROPERTY_DESCRIPTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner {
  public static final String JSON_PROPERTY_TYPE = "type";
  
  private IdentifierType type;

  public static final String JSON_PROPERTY_REGEX = "regex";
  
  private String regex;

  public static final String JSON_PROPERTY_NAME = "name";
  
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  
  private String description;

  public BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner() { 
  }

  public BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner type( IdentifierType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public IdentifierType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType( IdentifierType type) {
    this.type = type;
  }


  public BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner regex( String regex) {
    this.regex = regex;
    return this;
  }

  /**
   * A regex that can be used for validation of the field
   * @return regex
   */
  

  @JsonProperty(value = JSON_PROPERTY_REGEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRegex() {
    return regex;
  }


  @JsonProperty(value = JSON_PROPERTY_REGEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegex( String regex) {
    this.regex = regex;
  }


  public BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner name( String name) {
    this.name = name;
    return this;
  }

  /**
   * The common name of the field
   * @return name
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName( String name) {
    this.name = name;
  }


  public BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner description( String description) {
    this.description = description;
    return this;
  }

  /**
   * The description of the field and/or where to find it
   * @return description
   */
  

  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription( String description) {
    this.description = description;
  }


  /**
   * Return true if this bank_metadata_features_decoupled_flow_available_identifiers_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner bankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner = (BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner) o;
    return Objects.equals(this.type, bankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner.type) &&
        Objects.equals(this.regex, bankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner.regex) &&
        Objects.equals(this.name, bankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner.name) &&
        Objects.equals(this.description, bankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, regex, name, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankMetadataFeaturesDecoupledFlowAvailableIdentifiersInner {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    regex: ").append(toIndentedString(regex)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `regex` to the URL query string
    if (getRegex() != null) {
      joiner.add(String.format(Locale.ROOT, "%sregex%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRegex()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    return joiner.toString();
  }
}

