/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import nz.co.blink.debit.dto.v1.BankMetadataFeaturesCardPayment;
import nz.co.blink.debit.dto.v1.BankMetadataFeaturesDecoupledFlow;
import nz.co.blink.debit.dto.v1.BankMetadataFeaturesEnduringConsent;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The available bank features
 */
@JsonPropertyOrder({
  BankMetadataFeatures.JSON_PROPERTY_ENDURING_CONSENT,
  BankMetadataFeatures.JSON_PROPERTY_DECOUPLED_FLOW,
  BankMetadataFeatures.JSON_PROPERTY_CARD_PAYMENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BankMetadataFeatures {
  public static final String JSON_PROPERTY_ENDURING_CONSENT = "enduring_consent";
  
  private BankMetadataFeaturesEnduringConsent enduringConsent;

  public static final String JSON_PROPERTY_DECOUPLED_FLOW = "decoupled_flow";
  
  private BankMetadataFeaturesDecoupledFlow decoupledFlow;

  public static final String JSON_PROPERTY_CARD_PAYMENT = "card_payment";
  
  private BankMetadataFeaturesCardPayment cardPayment;

  public BankMetadataFeatures() { 
  }

  public BankMetadataFeatures enduringConsent( BankMetadataFeaturesEnduringConsent enduringConsent) {
    this.enduringConsent = enduringConsent;
    return this;
  }

  /**
   * Get enduringConsent
   * @return enduringConsent
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_ENDURING_CONSENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BankMetadataFeaturesEnduringConsent getEnduringConsent() {
    return enduringConsent;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDURING_CONSENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnduringConsent( BankMetadataFeaturesEnduringConsent enduringConsent) {
    this.enduringConsent = enduringConsent;
  }


  public BankMetadataFeatures decoupledFlow( BankMetadataFeaturesDecoupledFlow decoupledFlow) {
    this.decoupledFlow = decoupledFlow;
    return this;
  }

  /**
   * Get decoupledFlow
   * @return decoupledFlow
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_DECOUPLED_FLOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BankMetadataFeaturesDecoupledFlow getDecoupledFlow() {
    return decoupledFlow;
  }


  @JsonProperty(value = JSON_PROPERTY_DECOUPLED_FLOW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDecoupledFlow( BankMetadataFeaturesDecoupledFlow decoupledFlow) {
    this.decoupledFlow = decoupledFlow;
  }


  public BankMetadataFeatures cardPayment( BankMetadataFeaturesCardPayment cardPayment) {
    this.cardPayment = cardPayment;
    return this;
  }

  /**
   * Get cardPayment
   * @return cardPayment
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CARD_PAYMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BankMetadataFeaturesCardPayment getCardPayment() {
    return cardPayment;
  }


  @JsonProperty(value = JSON_PROPERTY_CARD_PAYMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCardPayment( BankMetadataFeaturesCardPayment cardPayment) {
    this.cardPayment = cardPayment;
  }


  /**
   * Return true if this bank_metadata_features object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankMetadataFeatures bankMetadataFeatures = (BankMetadataFeatures) o;
    return Objects.equals(this.enduringConsent, bankMetadataFeatures.enduringConsent) &&
        Objects.equals(this.decoupledFlow, bankMetadataFeatures.decoupledFlow) &&
        Objects.equals(this.cardPayment, bankMetadataFeatures.cardPayment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enduringConsent, decoupledFlow, cardPayment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankMetadataFeatures {\n");
    sb.append("    enduringConsent: ").append(toIndentedString(enduringConsent)).append("\n");
    sb.append("    decoupledFlow: ").append(toIndentedString(decoupledFlow)).append("\n");
    sb.append("    cardPayment: ").append(toIndentedString(cardPayment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `enduring_consent` to the URL query string
    if (getEnduringConsent() != null) {
      joiner.add(getEnduringConsent().toUrlQueryString(prefix + "enduring_consent" + suffix));
    }

    // add `decoupled_flow` to the URL query string
    if (getDecoupledFlow() != null) {
      joiner.add(getDecoupledFlow().toUrlQueryString(prefix + "decoupled_flow" + suffix));
    }

    // add `card_payment` to the URL query string
    if (getCardPayment() != null) {
      joiner.add(getCardPayment().toUrlQueryString(prefix + "card_payment" + suffix));
    }

    return joiner.toString();
  }
}

