/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import nz.co.blink.debit.dto.v1.CardNetwork;
import nz.co.blink.debit.dto.v1.CardPaymentType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The card payment feature
 */
@JsonPropertyOrder({
  BankMetadataFeaturesCardPayment.JSON_PROPERTY_ENABLED,
  BankMetadataFeaturesCardPayment.JSON_PROPERTY_ALLOWED_CARD_PAYMENT_TYPES,
  BankMetadataFeaturesCardPayment.JSON_PROPERTY_ALLOWED_CARD_NETWORKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BankMetadataFeaturesCardPayment {
  public static final String JSON_PROPERTY_ENABLED = "enabled";
  
  private Boolean enabled;

  public static final String JSON_PROPERTY_ALLOWED_CARD_PAYMENT_TYPES = "allowed_card_payment_types";
  
  private List<CardPaymentType> allowedCardPaymentTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_ALLOWED_CARD_NETWORKS = "allowed_card_networks";
  
  private List<CardNetwork> allowedCardNetworks = new ArrayList<>();

  public BankMetadataFeaturesCardPayment() { 
  }

  public BankMetadataFeaturesCardPayment enabled( Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Whether card payment is enabled.
   * @return enabled
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnabled( Boolean enabled) {
    this.enabled = enabled;
  }


  public BankMetadataFeaturesCardPayment allowedCardPaymentTypes( List<CardPaymentType> allowedCardPaymentTypes) {
    this.allowedCardPaymentTypes = allowedCardPaymentTypes;
    return this;
  }

  public BankMetadataFeaturesCardPayment addAllowedCardPaymentTypesItem(CardPaymentType allowedCardPaymentTypesItem) {
    if (this.allowedCardPaymentTypes == null) {
      this.allowedCardPaymentTypes = new ArrayList<>();
    }
    this.allowedCardPaymentTypes.add(allowedCardPaymentTypesItem);
    return this;
  }

  /**
   * The allowed card payment types.
   * @return allowedCardPaymentTypes
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_ALLOWED_CARD_PAYMENT_TYPES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<CardPaymentType> getAllowedCardPaymentTypes() {
    return allowedCardPaymentTypes;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOWED_CARD_PAYMENT_TYPES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAllowedCardPaymentTypes( List<CardPaymentType> allowedCardPaymentTypes) {
    this.allowedCardPaymentTypes = allowedCardPaymentTypes;
  }


  public BankMetadataFeaturesCardPayment allowedCardNetworks( List<CardNetwork> allowedCardNetworks) {
    this.allowedCardNetworks = allowedCardNetworks;
    return this;
  }

  public BankMetadataFeaturesCardPayment addAllowedCardNetworksItem(CardNetwork allowedCardNetworksItem) {
    if (this.allowedCardNetworks == null) {
      this.allowedCardNetworks = new ArrayList<>();
    }
    this.allowedCardNetworks.add(allowedCardNetworksItem);
    return this;
  }

  /**
   * The allowed card networks.
   * @return allowedCardNetworks
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_ALLOWED_CARD_NETWORKS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<CardNetwork> getAllowedCardNetworks() {
    return allowedCardNetworks;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOWED_CARD_NETWORKS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAllowedCardNetworks( List<CardNetwork> allowedCardNetworks) {
    this.allowedCardNetworks = allowedCardNetworks;
  }


  /**
   * Return true if this bank_metadata_features_card_payment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankMetadataFeaturesCardPayment bankMetadataFeaturesCardPayment = (BankMetadataFeaturesCardPayment) o;
    return Objects.equals(this.enabled, bankMetadataFeaturesCardPayment.enabled) &&
        Objects.equals(this.allowedCardPaymentTypes, bankMetadataFeaturesCardPayment.allowedCardPaymentTypes) &&
        Objects.equals(this.allowedCardNetworks, bankMetadataFeaturesCardPayment.allowedCardNetworks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, allowedCardPaymentTypes, allowedCardNetworks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankMetadataFeaturesCardPayment {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    allowedCardPaymentTypes: ").append(toIndentedString(allowedCardPaymentTypes)).append("\n");
    sb.append("    allowedCardNetworks: ").append(toIndentedString(allowedCardNetworks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `enabled` to the URL query string
    if (getEnabled() != null) {
      joiner.add(String.format(Locale.ROOT, "%senabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnabled()))));
    }

    // add `allowed_card_payment_types` to the URL query string
    if (getAllowedCardPaymentTypes() != null) {
      for (int i = 0; i < getAllowedCardPaymentTypes().size(); i++) {
        if (getAllowedCardPaymentTypes().get(i) != null) {
          joiner.add(String.format(Locale.ROOT, "%sallowed_card_payment_types%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(getAllowedCardPaymentTypes().get(i)))));
        }
      }
    }

    // add `allowed_card_networks` to the URL query string
    if (getAllowedCardNetworks() != null) {
      for (int i = 0; i < getAllowedCardNetworks().size(); i++) {
        if (getAllowedCardNetworks().get(i) != null) {
          joiner.add(String.format(Locale.ROOT, "%sallowed_card_networks%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(getAllowedCardNetworks().get(i)))));
        }
      }
    }

    return joiner.toString();
  }
}

