/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import nz.co.blink.debit.dto.v1.CardNetwork;
import nz.co.blink.debit.dto.v1.ConsentDetail;
import nz.co.blink.debit.dto.v1.Payment;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The model for a consent.
 */
@JsonPropertyOrder({
  Consent.JSON_PROPERTY_CONSENT_ID,
  Consent.JSON_PROPERTY_STATUS,
  Consent.JSON_PROPERTY_CREATION_TIMESTAMP,
  Consent.JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP,
  Consent.JSON_PROPERTY_DETAIL,
  Consent.JSON_PROPERTY_PAYMENTS,
  Consent.JSON_PROPERTY_CARD_NETWORK
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Consent {
  public static final String JSON_PROPERTY_CONSENT_ID = "consent_id";
  
  private UUID consentId;

  /**
   * The status of the consent
   */
  public enum StatusEnum {
    GATEWAY_AWAITING_SUBMISSION(String.valueOf("GatewayAwaitingSubmission")),
    
    GATEWAY_TIMEOUT(String.valueOf("GatewayTimeout")),
    
    AWAITING_AUTHORISATION(String.valueOf("AwaitingAuthorisation")),
    
    AUTHORISED(String.valueOf("Authorised")),
    
    CONSUMED(String.valueOf("Consumed")),
    
    REJECTED(String.valueOf("Rejected")),
    
    REVOKED(String.valueOf("Revoked"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  
  private StatusEnum status;

  public static final String JSON_PROPERTY_CREATION_TIMESTAMP = "creation_timestamp";
  
  private OffsetDateTime creationTimestamp;

  public static final String JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP = "status_updated_timestamp";
  
  private OffsetDateTime statusUpdatedTimestamp;

  public static final String JSON_PROPERTY_DETAIL = "detail";
  
  private ConsentDetail detail;

  public static final String JSON_PROPERTY_PAYMENTS = "payments";
  
  private List<@Valid Payment> payments = new ArrayList<>();

  public static final String JSON_PROPERTY_CARD_NETWORK = "card_network";
  
  private CardNetwork cardNetwork;

  public Consent() { 
  }

  public Consent consentId( UUID consentId) {
    this.consentId = consentId;
    return this;
  }

  /**
   * The consent ID
   * @return consentId
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONSENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getConsentId() {
    return consentId;
  }


  @JsonProperty(value = JSON_PROPERTY_CONSENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConsentId( UUID consentId) {
    this.consentId = consentId;
  }


  public Consent status( StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * The status of the consent
   * @return status
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus( StatusEnum status) {
    this.status = status;
  }


  public Consent creationTimestamp( OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

  /**
   * The timestamp that the consent was created
   * @return creationTimestamp
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CREATION_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreationTimestamp() {
    return creationTimestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreationTimestamp( OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }


  public Consent statusUpdatedTimestamp( OffsetDateTime statusUpdatedTimestamp) {
    this.statusUpdatedTimestamp = statusUpdatedTimestamp;
    return this;
  }

  /**
   * The time that the status was last updated
   * @return statusUpdatedTimestamp
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getStatusUpdatedTimestamp() {
    return statusUpdatedTimestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatusUpdatedTimestamp( OffsetDateTime statusUpdatedTimestamp) {
    this.statusUpdatedTimestamp = statusUpdatedTimestamp;
  }


  public Consent detail( ConsentDetail detail) {
    this.detail = detail;
    return this;
  }

  /**
   * Get detail
   * @return detail
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ConsentDetail getDetail() {
    return detail;
  }


  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDetail( ConsentDetail detail) {
    this.detail = detail;
  }


  public Consent payments( List<@Valid Payment> payments) {
    this.payments = payments;
    return this;
  }

  public Consent addPaymentsItem(Payment paymentsItem) {
    if (this.payments == null) {
      this.payments = new ArrayList<>();
    }
    this.payments.add(paymentsItem);
    return this;
  }

  /**
   * Payments associated with this consent, if any.
   * @return payments
   */
  
  @NotNull
  @Valid
 @Size(min=0)
  @JsonProperty(value = JSON_PROPERTY_PAYMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid Payment> getPayments() {
    return payments;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayments( List<@Valid Payment> payments) {
    this.payments = payments;
  }


  public Consent cardNetwork( CardNetwork cardNetwork) {
    this.cardNetwork = cardNetwork;
    return this;
  }

  /**
   * Get cardNetwork
   * @return cardNetwork
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CARD_NETWORK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CardNetwork getCardNetwork() {
    return cardNetwork;
  }


  @JsonProperty(value = JSON_PROPERTY_CARD_NETWORK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCardNetwork( CardNetwork cardNetwork) {
    this.cardNetwork = cardNetwork;
  }


  /**
   * Return true if this consent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Consent consent = (Consent) o;
    return Objects.equals(this.consentId, consent.consentId) &&
        Objects.equals(this.status, consent.status) &&
        Objects.equals(this.creationTimestamp, consent.creationTimestamp) &&
        Objects.equals(this.statusUpdatedTimestamp, consent.statusUpdatedTimestamp) &&
        Objects.equals(this.detail, consent.detail) &&
        Objects.equals(this.payments, consent.payments) &&
        Objects.equals(this.cardNetwork, consent.cardNetwork);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consentId, status, creationTimestamp, statusUpdatedTimestamp, detail, payments, cardNetwork);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Consent {\n");
    sb.append("    consentId: ").append(toIndentedString(consentId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
    sb.append("    statusUpdatedTimestamp: ").append(toIndentedString(statusUpdatedTimestamp)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    cardNetwork: ").append(toIndentedString(cardNetwork)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `consent_id` to the URL query string
    if (getConsentId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sconsent_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConsentId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `creation_timestamp` to the URL query string
    if (getCreationTimestamp() != null) {
      joiner.add(String.format(Locale.ROOT, "%screation_timestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreationTimestamp()))));
    }

    // add `status_updated_timestamp` to the URL query string
    if (getStatusUpdatedTimestamp() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstatus_updated_timestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusUpdatedTimestamp()))));
    }

    // add `detail` to the URL query string
    if (getDetail() != null) {
      joiner.add(getDetail().toUrlQueryString(prefix + "detail" + suffix));
    }

    // add `payments` to the URL query string
    if (getPayments() != null) {
      for (int i = 0; i < getPayments().size(); i++) {
        if (getPayments().get(i) != null) {
          joiner.add(getPayments().get(i).toUrlQueryString(String.format(Locale.ROOT, "%spayments%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `card_network` to the URL query string
    if (getCardNetwork() != null) {
      joiner.add(String.format(Locale.ROOT, "%scard_network%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCardNetwork()))));
    }

    return joiner.toString();
  }
}

