/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The quick payment response
 */
@JsonPropertyOrder({
  CreateQuickPaymentResponse.JSON_PROPERTY_QUICK_PAYMENT_ID,
  CreateQuickPaymentResponse.JSON_PROPERTY_REDIRECT_URI
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CreateQuickPaymentResponse {
  public static final String JSON_PROPERTY_QUICK_PAYMENT_ID = "quick_payment_id";
  
  private UUID quickPaymentId;

  public static final String JSON_PROPERTY_REDIRECT_URI = "redirect_uri";
  
  private URI redirectUri;

  public CreateQuickPaymentResponse() { 
  }

  public CreateQuickPaymentResponse quickPaymentId( UUID quickPaymentId) {
    this.quickPaymentId = quickPaymentId;
    return this;
  }

  /**
   * The quick payment ID
   * @return quickPaymentId
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_QUICK_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getQuickPaymentId() {
    return quickPaymentId;
  }


  @JsonProperty(value = JSON_PROPERTY_QUICK_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuickPaymentId( UUID quickPaymentId) {
    this.quickPaymentId = quickPaymentId;
  }


  public CreateQuickPaymentResponse redirectUri( URI redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

  /**
   * The URL to redirect the user to, returned if the flow type is \&quot;redirect\&quot; or \&quot;gateway\&quot;
   * @return redirectUri
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getRedirectUri() {
    return redirectUri;
  }


  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedirectUri( URI redirectUri) {
    this.redirectUri = redirectUri;
  }


  /**
   * Return true if this Create_Quick_Payment_Response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateQuickPaymentResponse createQuickPaymentResponse = (CreateQuickPaymentResponse) o;
    return Objects.equals(this.quickPaymentId, createQuickPaymentResponse.quickPaymentId) &&
        Objects.equals(this.redirectUri, createQuickPaymentResponse.redirectUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quickPaymentId, redirectUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateQuickPaymentResponse {\n");
    sb.append("    quickPaymentId: ").append(toIndentedString(quickPaymentId)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `quick_payment_id` to the URL query string
    if (getQuickPaymentId() != null) {
      joiner.add(String.format(Locale.ROOT, "%squick_payment_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuickPaymentId()))));
    }

    // add `redirect_uri` to the URL query string
    if (getRedirectUri() != null) {
      joiner.add(String.format(Locale.ROOT, "%sredirect_uri%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRedirectUri()))));
    }

    return joiner.toString();
  }
}

