/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import nz.co.blink.debit.dto.v1.PaymentDetails;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The total volumes and values per currency.
 */
@JsonPropertyOrder({
  CurrencyDetails.JSON_PROPERTY_TOTAL_VOLUME,
  CurrencyDetails.JSON_PROPERTY_TOTAL_VALUE,
  CurrencyDetails.JSON_PROPERTY_PAYMENTS_BY_DATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CurrencyDetails {
  public static final String JSON_PROPERTY_TOTAL_VOLUME = "total_volume";
  
  private Integer totalVolume;

  public static final String JSON_PROPERTY_TOTAL_VALUE = "total_value";
  
  private String totalValue;

  public static final String JSON_PROPERTY_PAYMENTS_BY_DATE = "payments_by_date";
  
  private Map<String, PaymentDetails> paymentsByDate = new HashMap<>();

  public CurrencyDetails() { 
  }

  public CurrencyDetails totalVolume( Integer totalVolume) {
    this.totalVolume = totalVolume;
    return this;
  }

  /**
   * Total number of transactions.
   * @return totalVolume
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_TOTAL_VOLUME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getTotalVolume() {
    return totalVolume;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_VOLUME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalVolume( Integer totalVolume) {
    this.totalVolume = totalVolume;
  }


  public CurrencyDetails totalValue( String totalValue) {
    this.totalValue = totalValue;
    return this;
  }

  /**
   * Total value of transactions represented as a string to preserve decimal precision.
   * @return totalValue
   */
  
  @NotNull
 @Pattern(regexp="^\\d{1,13}\\.\\d{1,2}$")
  @JsonProperty(value = JSON_PROPERTY_TOTAL_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTotalValue() {
    return totalValue;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalValue( String totalValue) {
    this.totalValue = totalValue;
  }


  public CurrencyDetails paymentsByDate( Map<String, PaymentDetails> paymentsByDate) {
    this.paymentsByDate = paymentsByDate;
    return this;
  }

  public CurrencyDetails putPaymentsByDateItem(String key, PaymentDetails paymentsByDateItem) {
    if (this.paymentsByDate == null) {
      this.paymentsByDate = new HashMap<>();
    }
    this.paymentsByDate.put(key, paymentsByDateItem);
    return this;
  }

  /**
   * The mapping of payment details to a date.
   * @return paymentsByDate
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PAYMENTS_BY_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, PaymentDetails> getPaymentsByDate() {
    return paymentsByDate;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENTS_BY_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentsByDate( Map<String, PaymentDetails> paymentsByDate) {
    this.paymentsByDate = paymentsByDate;
  }


  /**
   * Return true if this currency-details object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrencyDetails currencyDetails = (CurrencyDetails) o;
    return Objects.equals(this.totalVolume, currencyDetails.totalVolume) &&
        Objects.equals(this.totalValue, currencyDetails.totalValue) &&
        Objects.equals(this.paymentsByDate, currencyDetails.paymentsByDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalVolume, totalValue, paymentsByDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrencyDetails {\n");
    sb.append("    totalVolume: ").append(toIndentedString(totalVolume)).append("\n");
    sb.append("    totalValue: ").append(toIndentedString(totalValue)).append("\n");
    sb.append("    paymentsByDate: ").append(toIndentedString(paymentsByDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `total_volume` to the URL query string
    if (getTotalVolume() != null) {
      joiner.add(String.format(Locale.ROOT, "%stotal_volume%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalVolume()))));
    }

    // add `total_value` to the URL query string
    if (getTotalValue() != null) {
      joiner.add(String.format(Locale.ROOT, "%stotal_value%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalValue()))));
    }

    // add `payments_by_date` to the URL query string
    if (getPaymentsByDate() != null) {
      for (String _key : getPaymentsByDate().keySet()) {
        if (getPaymentsByDate().get(_key) != null) {
          joiner.add(getPaymentsByDate().get(_key).toUrlQueryString(String.format(Locale.ROOT, "%spayments_by_date%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

