/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import nz.co.blink.debit.dto.v1.AuthFlowDetail;
import nz.co.blink.debit.dto.v1.Bank;
import nz.co.blink.debit.dto.v1.IdentifierType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


import nz.co.blink.debit.dto.JSON;
/**
 * The details for a Decoupled flow.
 */
@JsonPropertyOrder({
  DecoupledFlow.JSON_PROPERTY_BANK,
  DecoupledFlow.JSON_PROPERTY_IDENTIFIER_TYPE,
  DecoupledFlow.JSON_PROPERTY_IDENTIFIER_VALUE,
  DecoupledFlow.JSON_PROPERTY_CALLBACK_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class DecoupledFlow extends AuthFlowDetail {
  public static final String JSON_PROPERTY_BANK = "bank";
  
  private Bank bank;

  public static final String JSON_PROPERTY_IDENTIFIER_TYPE = "identifier_type";
  
  private IdentifierType identifierType;

  public static final String JSON_PROPERTY_IDENTIFIER_VALUE = "identifier_value";
  
  private String identifierValue;

  public static final String JSON_PROPERTY_CALLBACK_URL = "callback_url";
  
  private URI callbackUrl;

  public DecoupledFlow() { 
  }

  public DecoupledFlow bank( Bank bank) {
    this.bank = bank;
    return this;
  }

  /**
   * Get bank
   * @return bank
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_BANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Bank getBank() {
    return bank;
  }


  @JsonProperty(value = JSON_PROPERTY_BANK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBank( Bank bank) {
    this.bank = bank;
  }


  public DecoupledFlow identifierType( IdentifierType identifierType) {
    this.identifierType = identifierType;
    return this;
  }

  /**
   * Get identifierType
   * @return identifierType
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_IDENTIFIER_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public IdentifierType getIdentifierType() {
    return identifierType;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTIFIER_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifierType( IdentifierType identifierType) {
    this.identifierType = identifierType;
  }


  public DecoupledFlow identifierValue( String identifierValue) {
    this.identifierValue = identifierValue;
    return this;
  }

  /**
   * The identifier value.
   * @return identifierValue
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_IDENTIFIER_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getIdentifierValue() {
    return identifierValue;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTIFIER_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifierValue( String identifierValue) {
    this.identifierValue = identifierValue;
  }


  public DecoupledFlow callbackUrl( URI callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

  /**
   * A callback URL to call once the consent status has been updated using decoupled flow. Blink will also append the &#x60;cid&#x60; (the Consent ID) in an additional URL parameter. This is sent to your api as a GET request and will be retried up to 3 times if 5xx errors are received from your server.
   * @return callbackUrl
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CALLBACK_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getCallbackUrl() {
    return callbackUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_CALLBACK_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallbackUrl( URI callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public DecoupledFlow putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  @Override
  public DecoupledFlow type( TypeEnum type) {
    this.setType(type);
    return this;
  }

  /**
   * Return true if this decoupled-flow object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DecoupledFlow decoupledFlow = (DecoupledFlow) o;
    return Objects.equals(this.bank, decoupledFlow.bank) &&
        Objects.equals(this.identifierType, decoupledFlow.identifierType) &&
        Objects.equals(this.identifierValue, decoupledFlow.identifierValue) &&
        Objects.equals(this.callbackUrl, decoupledFlow.callbackUrl)&&
        Objects.equals(this.additionalProperties, decoupledFlow.additionalProperties) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bank, identifierType, identifierValue, callbackUrl, super.hashCode(), additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DecoupledFlow {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("    identifierType: ").append(toIndentedString(identifierType)).append("\n");
    sb.append("    identifierValue: ").append(toIndentedString(identifierValue)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `bank` to the URL query string
    if (getBank() != null) {
      joiner.add(String.format(Locale.ROOT, "%sbank%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBank()))));
    }

    // add `identifier_type` to the URL query string
    if (getIdentifierType() != null) {
      joiner.add(String.format(Locale.ROOT, "%sidentifier_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIdentifierType()))));
    }

    // add `identifier_value` to the URL query string
    if (getIdentifierValue() != null) {
      joiner.add(String.format(Locale.ROOT, "%sidentifier_value%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIdentifierValue()))));
    }

    // add `callback_url` to the URL query string
    if (getCallbackUrl() != null) {
      joiner.add(String.format(Locale.ROOT, "%scallback_url%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCallbackUrl()))));
    }

    return joiner.toString();
  }
static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("decoupled-flow", DecoupledFlow.class);
  JSON.registerDiscriminator(DecoupledFlow.class, "type", mappings);
}
}

