/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The detailed error response.
 */
@JsonPropertyOrder({
  DetailErrorResponseModel.JSON_PROPERTY_TIMESTAMP,
  DetailErrorResponseModel.JSON_PROPERTY_STATUS,
  DetailErrorResponseModel.JSON_PROPERTY_ERROR,
  DetailErrorResponseModel.JSON_PROPERTY_MESSAGE,
  DetailErrorResponseModel.JSON_PROPERTY_PATH,
  DetailErrorResponseModel.JSON_PROPERTY_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class DetailErrorResponseModel {
  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_STATUS = "status";
  
  private Integer status;

  public static final String JSON_PROPERTY_ERROR = "error";
  
  private String error;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  
  private String message;

  public static final String JSON_PROPERTY_PATH = "path";
  
  private String path;

  public static final String JSON_PROPERTY_CODE = "code";
  
  private String code;

  public DetailErrorResponseModel() { 
  }

  public DetailErrorResponseModel timestamp( OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * The error timestamp.
   * @return timestamp
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp( OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public DetailErrorResponseModel status( Integer status) {
    this.status = status;
    return this;
  }

  /**
   * The status code.
   * @return status
   */
  

  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus( Integer status) {
    this.status = status;
  }


  public DetailErrorResponseModel error( String error) {
    this.error = error;
    return this;
  }

  /**
   * The title of the error code.
   * @return error
   */
  

  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getError() {
    return error;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError( String error) {
    this.error = error;
  }


  public DetailErrorResponseModel message( String message) {
    this.message = message;
    return this;
  }

  /**
   * The error detail.
   * @return message
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage( String message) {
    this.message = message;
  }


  public DetailErrorResponseModel path( String path) {
    this.path = path;
    return this;
  }

  /**
   * The requested path when the error was triggered.
   * @return path
   */
  

  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPath( String path) {
    this.path = path;
  }


  public DetailErrorResponseModel code( String code) {
    this.code = code;
    return this;
  }

  /**
   * A code supplied by BlinkPay to reference the error type
   * @return code
   */
  

  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode( String code) {
    this.code = code;
  }


  /**
   * Return true if this detail-error-response-model object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailErrorResponseModel detailErrorResponseModel = (DetailErrorResponseModel) o;
    return Objects.equals(this.timestamp, detailErrorResponseModel.timestamp) &&
        Objects.equals(this.status, detailErrorResponseModel.status) &&
        Objects.equals(this.error, detailErrorResponseModel.error) &&
        Objects.equals(this.message, detailErrorResponseModel.message) &&
        Objects.equals(this.path, detailErrorResponseModel.path) &&
        Objects.equals(this.code, detailErrorResponseModel.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, status, error, message, path, code);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailErrorResponseModel {\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(String.format(Locale.ROOT, "%serror%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getError()))));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format(Locale.ROOT, "%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    // add `path` to the URL query string
    if (getPath() != null) {
      joiner.add(String.format(Locale.ROOT, "%spath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPath()))));
    }

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format(Locale.ROOT, "%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    return joiner.toString();
  }
}

