/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import nz.co.blink.debit.dto.v1.Amount;
import nz.co.blink.debit.dto.v1.AuthFlow;
import nz.co.blink.debit.dto.v1.Period;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The model for an enduring consent request, relating to multiple payments.
 */
@JsonPropertyOrder({
  EnduringConsentRequest.JSON_PROPERTY_TYPE,
  EnduringConsentRequest.JSON_PROPERTY_FLOW,
  EnduringConsentRequest.JSON_PROPERTY_FROM_TIMESTAMP,
  EnduringConsentRequest.JSON_PROPERTY_EXPIRY_TIMESTAMP,
  EnduringConsentRequest.JSON_PROPERTY_PERIOD,
  EnduringConsentRequest.JSON_PROPERTY_MAXIMUM_AMOUNT_PERIOD,
  EnduringConsentRequest.JSON_PROPERTY_MAXIMUM_AMOUNT_PAYMENT,
  EnduringConsentRequest.JSON_PROPERTY_HASHED_CUSTOMER_IDENTIFIER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class EnduringConsentRequest {
  /**
   * Whether the consent is single or enduring.
   */
  public enum TypeEnum {
    SINGLE(String.valueOf("single")),
    
    ENDURING(String.valueOf("enduring"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  
  private TypeEnum type;

  public static final String JSON_PROPERTY_FLOW = "flow";
  
  private AuthFlow flow;

  public static final String JSON_PROPERTY_FROM_TIMESTAMP = "from_timestamp";
  
  private OffsetDateTime fromTimestamp;

  public static final String JSON_PROPERTY_EXPIRY_TIMESTAMP = "expiry_timestamp";
  
  private OffsetDateTime expiryTimestamp;

  public static final String JSON_PROPERTY_PERIOD = "period";
  
  private Period period;

  public static final String JSON_PROPERTY_MAXIMUM_AMOUNT_PERIOD = "maximum_amount_period";
  
  private Amount maximumAmountPeriod;

  public static final String JSON_PROPERTY_MAXIMUM_AMOUNT_PAYMENT = "maximum_amount_payment";
  
  private Amount maximumAmountPayment;

  public static final String JSON_PROPERTY_HASHED_CUSTOMER_IDENTIFIER = "hashed_customer_identifier";
  
  private String hashedCustomerIdentifier;

  public EnduringConsentRequest() { 
  }

  @JsonCreator
  public EnduringConsentRequest(
    @JsonProperty(JSON_PROPERTY_TYPE) TypeEnum type
  ) {
  this();
    this.type = type;
  }

  /**
   * Whether the consent is single or enduring.
   * @return type
   */
  

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TypeEnum getType() {
    return type;
  }




  public EnduringConsentRequest flow( AuthFlow flow) {
    this.flow = flow;
    return this;
  }

  /**
   * Get flow
   * @return flow
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_FLOW, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AuthFlow getFlow() {
    return flow;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOW, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlow( AuthFlow flow) {
    this.flow = flow;
  }


  public EnduringConsentRequest fromTimestamp( OffsetDateTime fromTimestamp) {
    this.fromTimestamp = fromTimestamp;
    return this;
  }

  /**
   * The ISO 8601 start date to calculate the periods for which to calculate the consent period.
   * @return fromTimestamp
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_FROM_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getFromTimestamp() {
    return fromTimestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromTimestamp( OffsetDateTime fromTimestamp) {
    this.fromTimestamp = fromTimestamp;
  }


  public EnduringConsentRequest expiryTimestamp( OffsetDateTime expiryTimestamp) {
    this.expiryTimestamp = expiryTimestamp;
    return this;
  }

  /**
   * The ISO 8601 timeout for when an enduring consent will expire. If this field is blank, an indefinite request will be attempted.
   * @return expiryTimestamp
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_EXPIRY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getExpiryTimestamp() {
    return expiryTimestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiryTimestamp( OffsetDateTime expiryTimestamp) {
    this.expiryTimestamp = expiryTimestamp;
  }


  public EnduringConsentRequest period( Period period) {
    this.period = period;
    return this;
  }

  /**
   * Get period
   * @return period
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Period getPeriod() {
    return period;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeriod( Period period) {
    this.period = period;
  }


  public EnduringConsentRequest maximumAmountPeriod( Amount maximumAmountPeriod) {
    this.maximumAmountPeriod = maximumAmountPeriod;
    return this;
  }

  /**
   * Get maximumAmountPeriod
   * @return maximumAmountPeriod
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_MAXIMUM_AMOUNT_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Amount getMaximumAmountPeriod() {
    return maximumAmountPeriod;
  }


  @JsonProperty(value = JSON_PROPERTY_MAXIMUM_AMOUNT_PERIOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaximumAmountPeriod( Amount maximumAmountPeriod) {
    this.maximumAmountPeriod = maximumAmountPeriod;
  }


  public EnduringConsentRequest maximumAmountPayment( Amount maximumAmountPayment) {
    this.maximumAmountPayment = maximumAmountPayment;
    return this;
  }

  /**
   * Get maximumAmountPayment
   * @return maximumAmountPayment
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_MAXIMUM_AMOUNT_PAYMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Amount getMaximumAmountPayment() {
    return maximumAmountPayment;
  }


  @JsonProperty(value = JSON_PROPERTY_MAXIMUM_AMOUNT_PAYMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaximumAmountPayment( Amount maximumAmountPayment) {
    this.maximumAmountPayment = maximumAmountPayment;
  }


  public EnduringConsentRequest hashedCustomerIdentifier( String hashedCustomerIdentifier) {
    this.hashedCustomerIdentifier = hashedCustomerIdentifier;
    return this;
  }

  /**
   * The hashed unique ID of the customer e.g. customer internal ID. SHA-256 is recommended.
   * @return hashedCustomerIdentifier
   */
  

  @JsonProperty(value = JSON_PROPERTY_HASHED_CUSTOMER_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHashedCustomerIdentifier() {
    return hashedCustomerIdentifier;
  }


  @JsonProperty(value = JSON_PROPERTY_HASHED_CUSTOMER_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHashedCustomerIdentifier( String hashedCustomerIdentifier) {
    this.hashedCustomerIdentifier = hashedCustomerIdentifier;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public EnduringConsentRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  /**
   * Return true if this enduring-consent-request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnduringConsentRequest enduringConsentRequest = (EnduringConsentRequest) o;
    return Objects.equals(this.type, enduringConsentRequest.type) &&
        Objects.equals(this.flow, enduringConsentRequest.flow) &&
        Objects.equals(this.fromTimestamp, enduringConsentRequest.fromTimestamp) &&
        Objects.equals(this.expiryTimestamp, enduringConsentRequest.expiryTimestamp) &&
        Objects.equals(this.period, enduringConsentRequest.period) &&
        Objects.equals(this.maximumAmountPeriod, enduringConsentRequest.maximumAmountPeriod) &&
        Objects.equals(this.maximumAmountPayment, enduringConsentRequest.maximumAmountPayment) &&
        Objects.equals(this.hashedCustomerIdentifier, enduringConsentRequest.hashedCustomerIdentifier)&&
        Objects.equals(this.additionalProperties, enduringConsentRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, flow, fromTimestamp, expiryTimestamp, period, maximumAmountPeriod, maximumAmountPayment, hashedCustomerIdentifier, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnduringConsentRequest {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    flow: ").append(toIndentedString(flow)).append("\n");
    sb.append("    fromTimestamp: ").append(toIndentedString(fromTimestamp)).append("\n");
    sb.append("    expiryTimestamp: ").append(toIndentedString(expiryTimestamp)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    maximumAmountPeriod: ").append(toIndentedString(maximumAmountPeriod)).append("\n");
    sb.append("    maximumAmountPayment: ").append(toIndentedString(maximumAmountPayment)).append("\n");
    sb.append("    hashedCustomerIdentifier: ").append(toIndentedString(hashedCustomerIdentifier)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `flow` to the URL query string
    if (getFlow() != null) {
      joiner.add(getFlow().toUrlQueryString(prefix + "flow" + suffix));
    }

    // add `from_timestamp` to the URL query string
    if (getFromTimestamp() != null) {
      joiner.add(String.format(Locale.ROOT, "%sfrom_timestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFromTimestamp()))));
    }

    // add `expiry_timestamp` to the URL query string
    if (getExpiryTimestamp() != null) {
      joiner.add(String.format(Locale.ROOT, "%sexpiry_timestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiryTimestamp()))));
    }

    // add `period` to the URL query string
    if (getPeriod() != null) {
      joiner.add(String.format(Locale.ROOT, "%speriod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPeriod()))));
    }

    // add `maximum_amount_period` to the URL query string
    if (getMaximumAmountPeriod() != null) {
      joiner.add(getMaximumAmountPeriod().toUrlQueryString(prefix + "maximum_amount_period" + suffix));
    }

    // add `maximum_amount_payment` to the URL query string
    if (getMaximumAmountPayment() != null) {
      joiner.add(getMaximumAmountPayment().toUrlQueryString(prefix + "maximum_amount_payment" + suffix));
    }

    // add `hashed_customer_identifier` to the URL query string
    if (getHashedCustomerIdentifier() != null) {
      joiner.add(String.format(Locale.ROOT, "%shashed_customer_identifier%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHashedCustomerIdentifier()))));
    }

    return joiner.toString();
  }
}

