/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import java.util.UUID;
import nz.co.blink.debit.dto.v1.Pcr;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The PCR and to use in the &#x60;full_refund&#x60; request.
 */
@JsonPropertyOrder({
  FullRefundRequest.JSON_PROPERTY_PAYMENT_ID,
  FullRefundRequest.JSON_PROPERTY_TYPE,
  FullRefundRequest.JSON_PROPERTY_PCR,
  FullRefundRequest.JSON_PROPERTY_CONSENT_REDIRECT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class FullRefundRequest {
  public static final String JSON_PROPERTY_PAYMENT_ID = "payment_id";
  
  private UUID paymentId;

  /**
   * The refund type.
   */
  public enum TypeEnum {
    ACCOUNT_NUMBER(String.valueOf("account_number")),
    
    PARTIAL_REFUND(String.valueOf("partial_refund")),
    
    FULL_REFUND(String.valueOf("full_refund"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  
  private TypeEnum type;

  public static final String JSON_PROPERTY_PCR = "pcr";
  
  private Pcr pcr;

  public static final String JSON_PROPERTY_CONSENT_REDIRECT = "consent_redirect";
  
  private URI consentRedirect;

  public FullRefundRequest() { 
  }

  public FullRefundRequest paymentId( UUID paymentId) {
    this.paymentId = paymentId;
    return this;
  }

  /**
   * The payment ID. The payment must have a status of &#x60;AcceptedSettlementCompleted&#x60;.
   * @return paymentId
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getPaymentId() {
    return paymentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentId( UUID paymentId) {
    this.paymentId = paymentId;
  }


  public FullRefundRequest type( TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The refund type.
   * @return type
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType( TypeEnum type) {
    this.type = type;
  }


  public FullRefundRequest pcr( Pcr pcr) {
    this.pcr = pcr;
    return this;
  }

  /**
   * Get pcr
   * @return pcr
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PCR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Pcr getPcr() {
    return pcr;
  }


  @JsonProperty(value = JSON_PROPERTY_PCR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPcr( Pcr pcr) {
    this.pcr = pcr;
  }


  public FullRefundRequest consentRedirect( URI consentRedirect) {
    this.consentRedirect = consentRedirect;
    return this;
  }

  /**
   * The URI that the merchant will need to visit to authorise the refund payment from their bank, if applicable.
   * @return consentRedirect
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONSENT_REDIRECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getConsentRedirect() {
    return consentRedirect;
  }


  @JsonProperty(value = JSON_PROPERTY_CONSENT_REDIRECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConsentRedirect( URI consentRedirect) {
    this.consentRedirect = consentRedirect;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public FullRefundRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  /**
   * Return true if this full-refund-request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullRefundRequest fullRefundRequest = (FullRefundRequest) o;
    return Objects.equals(this.paymentId, fullRefundRequest.paymentId) &&
        Objects.equals(this.type, fullRefundRequest.type) &&
        Objects.equals(this.pcr, fullRefundRequest.pcr) &&
        Objects.equals(this.consentRedirect, fullRefundRequest.consentRedirect)&&
        Objects.equals(this.additionalProperties, fullRefundRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentId, type, pcr, consentRedirect, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullRefundRequest {\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    pcr: ").append(toIndentedString(pcr)).append("\n");
    sb.append("    consentRedirect: ").append(toIndentedString(consentRedirect)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `payment_id` to the URL query string
    if (getPaymentId() != null) {
      joiner.add(String.format(Locale.ROOT, "%spayment_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentId()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `pcr` to the URL query string
    if (getPcr() != null) {
      joiner.add(getPcr().toUrlQueryString(prefix + "pcr" + suffix));
    }

    // add `consent_redirect` to the URL query string
    if (getConsentRedirect() != null) {
      joiner.add(String.format(Locale.ROOT, "%sconsent_redirect%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConsentRedirect()))));
    }

    return joiner.toString();
  }
}

