/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The breakdown of payment details.
 */
@JsonPropertyOrder({
  PaymentDetailsBreakdown.JSON_PROPERTY_NETWORK,
  PaymentDetailsBreakdown.JSON_PROPERTY_VOLUME,
  PaymentDetailsBreakdown.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class PaymentDetailsBreakdown {
  public static final String JSON_PROPERTY_NETWORK = "network";
  
  private String network;

  public static final String JSON_PROPERTY_VOLUME = "volume";
  
  private Integer volume;

  public static final String JSON_PROPERTY_VALUE = "value";
  
  private String value;

  public PaymentDetailsBreakdown() { 
  }

  public PaymentDetailsBreakdown network( String network) {
    this.network = network;
    return this;
  }

  /**
   * The payment rails or card network. Values are: a2a, visa, mastercard, amex, discover, dinersclub, jcb
   * @return network
   */
  

  @JsonProperty(value = JSON_PROPERTY_NETWORK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNetwork() {
    return network;
  }


  @JsonProperty(value = JSON_PROPERTY_NETWORK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetwork( String network) {
    this.network = network;
  }


  public PaymentDetailsBreakdown volume( Integer volume) {
    this.volume = volume;
    return this;
  }

  /**
   * Number of transactions on this date.
   * @return volume
   */
  

  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getVolume() {
    return volume;
  }


  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolume( Integer volume) {
    this.volume = volume;
  }


  public PaymentDetailsBreakdown value( String value) {
    this.value = value;
    return this;
  }

  /**
   * Total value of transactions on this date.
   * @return value
   */
  
 @Pattern(regexp="^\\d{1,13}\\.\\d{1,2}$")
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue( String value) {
    this.value = value;
  }


  /**
   * Return true if this payment-details-breakdown object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentDetailsBreakdown paymentDetailsBreakdown = (PaymentDetailsBreakdown) o;
    return Objects.equals(this.network, paymentDetailsBreakdown.network) &&
        Objects.equals(this.volume, paymentDetailsBreakdown.volume) &&
        Objects.equals(this.value, paymentDetailsBreakdown.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(network, volume, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentDetailsBreakdown {\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `network` to the URL query string
    if (getNetwork() != null) {
      joiner.add(String.format(Locale.ROOT, "%snetwork%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNetwork()))));
    }

    // add `volume` to the URL query string
    if (getVolume() != null) {
      joiner.add(String.format(Locale.ROOT, "%svolume%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVolume()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    return joiner.toString();
  }
}

