/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import nz.co.blink.debit.dto.v1.PaymentRequest;
import nz.co.blink.debit.dto.v1.Refund;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The model for a payment.
 */
@JsonPropertyOrder({
  Payment.JSON_PROPERTY_PAYMENT_ID,
  Payment.JSON_PROPERTY_TYPE,
  Payment.JSON_PROPERTY_STATUS,
  Payment.JSON_PROPERTY_ACCEPTED_REASON,
  Payment.JSON_PROPERTY_CREATION_TIMESTAMP,
  Payment.JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP,
  Payment.JSON_PROPERTY_DETAIL,
  Payment.JSON_PROPERTY_REFUNDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Payment {
  public static final String JSON_PROPERTY_PAYMENT_ID = "payment_id";
  
  private UUID paymentId;

  /**
   * The type of payment (single or enduring).
   */
  public enum TypeEnum {
    SINGLE(String.valueOf("single")),
    
    ENDURING(String.valueOf("enduring"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  
  private TypeEnum type;

  /**
   * The status of the payment.
   */
  public enum StatusEnum {
    PENDING(String.valueOf("Pending")),
    
    ACCEPTED_SETTLEMENT_IN_PROCESS(String.valueOf("AcceptedSettlementInProcess")),
    
    ACCEPTED_SETTLEMENT_COMPLETED(String.valueOf("AcceptedSettlementCompleted")),
    
    REJECTED(String.valueOf("Rejected"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  
  private StatusEnum status;

  /**
   * The reason for &#x60;AcceptedSettlementCompleted&#x60;.
   */
  public enum AcceptedReasonEnum {
    SOURCE_BANK_PAYMENT_SENT(String.valueOf("source_bank_payment_sent")),
    
    CARD_NETWORK_ACCEPTED(String.valueOf("card_network_accepted"));

    private String value;

    AcceptedReasonEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AcceptedReasonEnum fromValue(String value) {
      for (AcceptedReasonEnum b : AcceptedReasonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACCEPTED_REASON = "accepted_reason";
  
  private AcceptedReasonEnum acceptedReason;

  public static final String JSON_PROPERTY_CREATION_TIMESTAMP = "creation_timestamp";
  
  private OffsetDateTime creationTimestamp;

  public static final String JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP = "status_updated_timestamp";
  
  private OffsetDateTime statusUpdatedTimestamp;

  public static final String JSON_PROPERTY_DETAIL = "detail";
  
  private PaymentRequest detail;

  public static final String JSON_PROPERTY_REFUNDS = "refunds";
  
  private List<@Valid Refund> refunds = new ArrayList<>();

  public Payment() { 
  }

  public Payment paymentId( UUID paymentId) {
    this.paymentId = paymentId;
    return this;
  }

  /**
   * The payment ID
   * @return paymentId
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getPaymentId() {
    return paymentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentId( UUID paymentId) {
    this.paymentId = paymentId;
  }


  public Payment type( TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The type of payment (single or enduring).
   * @return type
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType( TypeEnum type) {
    this.type = type;
  }


  public Payment status( StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * The status of the payment.
   * @return status
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus( StatusEnum status) {
    this.status = status;
  }


  public Payment acceptedReason( AcceptedReasonEnum acceptedReason) {
    this.acceptedReason = acceptedReason;
    return this;
  }

  /**
   * The reason for &#x60;AcceptedSettlementCompleted&#x60;.
   * @return acceptedReason
   */
  

  @JsonProperty(value = JSON_PROPERTY_ACCEPTED_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AcceptedReasonEnum getAcceptedReason() {
    return acceptedReason;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCEPTED_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcceptedReason( AcceptedReasonEnum acceptedReason) {
    this.acceptedReason = acceptedReason;
  }


  public Payment creationTimestamp( OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

  /**
   * The timestamp that the payment was created.
   * @return creationTimestamp
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CREATION_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreationTimestamp() {
    return creationTimestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreationTimestamp( OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }


  public Payment statusUpdatedTimestamp( OffsetDateTime statusUpdatedTimestamp) {
    this.statusUpdatedTimestamp = statusUpdatedTimestamp;
    return this;
  }

  /**
   * The timestamp that the payment status was last updated.
   * @return statusUpdatedTimestamp
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getStatusUpdatedTimestamp() {
    return statusUpdatedTimestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatusUpdatedTimestamp( OffsetDateTime statusUpdatedTimestamp) {
    this.statusUpdatedTimestamp = statusUpdatedTimestamp;
  }


  public Payment detail( PaymentRequest detail) {
    this.detail = detail;
    return this;
  }

  /**
   * Get detail
   * @return detail
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PaymentRequest getDetail() {
    return detail;
  }


  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDetail( PaymentRequest detail) {
    this.detail = detail;
  }


  public Payment refunds( List<@Valid Refund> refunds) {
    this.refunds = refunds;
    return this;
  }

  public Payment addRefundsItem(Refund refundsItem) {
    if (this.refunds == null) {
      this.refunds = new ArrayList<>();
    }
    this.refunds.add(refundsItem);
    return this;
  }

  /**
   * Refunds that are related to this payment, if any.
   * @return refunds
   */
  
  @NotNull
  @Valid
 @Size(min=0)
  @JsonProperty(value = JSON_PROPERTY_REFUNDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid Refund> getRefunds() {
    return refunds;
  }


  @JsonProperty(value = JSON_PROPERTY_REFUNDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRefunds( List<@Valid Refund> refunds) {
    this.refunds = refunds;
  }


  /**
   * Return true if this payment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payment payment = (Payment) o;
    return Objects.equals(this.paymentId, payment.paymentId) &&
        Objects.equals(this.type, payment.type) &&
        Objects.equals(this.status, payment.status) &&
        Objects.equals(this.acceptedReason, payment.acceptedReason) &&
        Objects.equals(this.creationTimestamp, payment.creationTimestamp) &&
        Objects.equals(this.statusUpdatedTimestamp, payment.statusUpdatedTimestamp) &&
        Objects.equals(this.detail, payment.detail) &&
        Objects.equals(this.refunds, payment.refunds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentId, type, status, acceptedReason, creationTimestamp, statusUpdatedTimestamp, detail, refunds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payment {\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    acceptedReason: ").append(toIndentedString(acceptedReason)).append("\n");
    sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
    sb.append("    statusUpdatedTimestamp: ").append(toIndentedString(statusUpdatedTimestamp)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    refunds: ").append(toIndentedString(refunds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `payment_id` to the URL query string
    if (getPaymentId() != null) {
      joiner.add(String.format(Locale.ROOT, "%spayment_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentId()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `accepted_reason` to the URL query string
    if (getAcceptedReason() != null) {
      joiner.add(String.format(Locale.ROOT, "%saccepted_reason%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAcceptedReason()))));
    }

    // add `creation_timestamp` to the URL query string
    if (getCreationTimestamp() != null) {
      joiner.add(String.format(Locale.ROOT, "%screation_timestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreationTimestamp()))));
    }

    // add `status_updated_timestamp` to the URL query string
    if (getStatusUpdatedTimestamp() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstatus_updated_timestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusUpdatedTimestamp()))));
    }

    // add `detail` to the URL query string
    if (getDetail() != null) {
      joiner.add(getDetail().toUrlQueryString(prefix + "detail" + suffix));
    }

    // add `refunds` to the URL query string
    if (getRefunds() != null) {
      for (int i = 0; i < getRefunds().size(); i++) {
        if (getRefunds().get(i) != null) {
          joiner.add(getRefunds().get(i).toUrlQueryString(String.format(Locale.ROOT, "%srefunds%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

