/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import nz.co.blink.debit.dto.v1.PaymentDetailsBreakdown;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The volumes and values for a given day.
 */
@JsonPropertyOrder({
  PaymentDetails.JSON_PROPERTY_VOLUME,
  PaymentDetails.JSON_PROPERTY_VALUE,
  PaymentDetails.JSON_PROPERTY_BREAKDOWN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class PaymentDetails {
  public static final String JSON_PROPERTY_VOLUME = "volume";
  
  private Integer volume;

  public static final String JSON_PROPERTY_VALUE = "value";
  
  private String value;

  public static final String JSON_PROPERTY_BREAKDOWN = "breakdown";
  
  private List<@Valid PaymentDetailsBreakdown> breakdown = new ArrayList<>();

  public PaymentDetails() { 
  }

  public PaymentDetails volume( Integer volume) {
    this.volume = volume;
    return this;
  }

  /**
   * Number of transactions on this date.
   * @return volume
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getVolume() {
    return volume;
  }


  @JsonProperty(value = JSON_PROPERTY_VOLUME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVolume( Integer volume) {
    this.volume = volume;
  }


  public PaymentDetails value( String value) {
    this.value = value;
    return this;
  }

  /**
   * Total value of transactions on this date.
   * @return value
   */
  
  @NotNull
 @Pattern(regexp="^\\d{1,13}\\.\\d{1,2}$")
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValue( String value) {
    this.value = value;
  }


  public PaymentDetails breakdown( List<@Valid PaymentDetailsBreakdown> breakdown) {
    this.breakdown = breakdown;
    return this;
  }

  public PaymentDetails addBreakdownItem(PaymentDetailsBreakdown breakdownItem) {
    if (this.breakdown == null) {
      this.breakdown = new ArrayList<>();
    }
    this.breakdown.add(breakdownItem);
    return this;
  }

  /**
   * Get breakdown
   * @return breakdown
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_BREAKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid PaymentDetailsBreakdown> getBreakdown() {
    return breakdown;
  }


  @JsonProperty(value = JSON_PROPERTY_BREAKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBreakdown( List<@Valid PaymentDetailsBreakdown> breakdown) {
    this.breakdown = breakdown;
  }


  /**
   * Return true if this payment-details object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentDetails paymentDetails = (PaymentDetails) o;
    return Objects.equals(this.volume, paymentDetails.volume) &&
        Objects.equals(this.value, paymentDetails.value) &&
        Objects.equals(this.breakdown, paymentDetails.breakdown);
  }

  @Override
  public int hashCode() {
    return Objects.hash(volume, value, breakdown);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentDetails {\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    breakdown: ").append(toIndentedString(breakdown)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `volume` to the URL query string
    if (getVolume() != null) {
      joiner.add(String.format(Locale.ROOT, "%svolume%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVolume()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    // add `breakdown` to the URL query string
    if (getBreakdown() != null) {
      for (int i = 0; i < getBreakdown().size(); i++) {
        if (getBreakdown().get(i) != null) {
          joiner.add(getBreakdown().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sbreakdown%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

