/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import nz.co.blink.debit.dto.v1.Amount;
import nz.co.blink.debit.dto.v1.Pcr;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The payment request model.
 */
@JsonPropertyOrder({
  PaymentRequest.JSON_PROPERTY_CONSENT_ID,
  PaymentRequest.JSON_PROPERTY_PCR,
  PaymentRequest.JSON_PROPERTY_AMOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class PaymentRequest {
  public static final String JSON_PROPERTY_CONSENT_ID = "consent_id";
  
  private UUID consentId;

  public static final String JSON_PROPERTY_PCR = "pcr";
  
  private Pcr pcr;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  
  private Amount amount;

  public PaymentRequest() { 
  }

  public PaymentRequest consentId( UUID consentId) {
    this.consentId = consentId;
    return this;
  }

  /**
   * The consent ID
   * @return consentId
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONSENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getConsentId() {
    return consentId;
  }


  @JsonProperty(value = JSON_PROPERTY_CONSENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConsentId( UUID consentId) {
    this.consentId = consentId;
  }


  public PaymentRequest pcr( Pcr pcr) {
    this.pcr = pcr;
    return this;
  }

  /**
   * Get pcr
   * @return pcr
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PCR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Pcr getPcr() {
    return pcr;
  }


  @JsonProperty(value = JSON_PROPERTY_PCR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPcr( Pcr pcr) {
    this.pcr = pcr;
  }


  public PaymentRequest amount( Amount amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  
  @Valid

  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Amount getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount( Amount amount) {
    this.amount = amount;
  }


  /**
   * Return true if this payment-request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRequest paymentRequest = (PaymentRequest) o;
    return Objects.equals(this.consentId, paymentRequest.consentId) &&
        Objects.equals(this.pcr, paymentRequest.pcr) &&
        Objects.equals(this.amount, paymentRequest.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consentId, pcr, amount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequest {\n");
    sb.append("    consentId: ").append(toIndentedString(consentId)).append("\n");
    sb.append("    pcr: ").append(toIndentedString(pcr)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `consent_id` to the URL query string
    if (getConsentId() != null) {
      joiner.add(String.format(Locale.ROOT, "%sconsent_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConsentId()))));
    }

    // add `pcr` to the URL query string
    if (getPcr() != null) {
      joiner.add(getPcr().toUrlQueryString(prefix + "pcr" + suffix));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(getAmount().toUrlQueryString(prefix + "amount" + suffix));
    }

    return joiner.toString();
  }
}

