/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * PCR (Particulars, code, reference) details.
 */
@JsonPropertyOrder({
  Pcr.JSON_PROPERTY_PARTICULARS,
  Pcr.JSON_PROPERTY_CODE,
  Pcr.JSON_PROPERTY_REFERENCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Pcr {
  public static final String JSON_PROPERTY_PARTICULARS = "particulars";
  
  private String particulars;

  public static final String JSON_PROPERTY_CODE = "code";
  
  private String code;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  
  private String reference;

  public Pcr() { 
  }

  public Pcr particulars( String particulars) {
    this.particulars = particulars;
    return this;
  }

  /**
   * The particulars
   * @return particulars
   */
  
  @NotNull
 @Pattern(regexp="[a-zA-Z0-9- &#\\?:_/,\\.']{1,12}") @Size(min=1,max=12)
  @JsonProperty(value = JSON_PROPERTY_PARTICULARS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getParticulars() {
    return particulars;
  }


  @JsonProperty(value = JSON_PROPERTY_PARTICULARS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParticulars( String particulars) {
    this.particulars = particulars;
  }


  public Pcr code( String code) {
    this.code = code;
    return this;
  }

  /**
   * The code
   * @return code
   */
  
 @Pattern(regexp="[a-zA-Z0-9- &#\\?:_/,\\.']{0,12}") @Size(max=12)
  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode( String code) {
    this.code = code;
  }


  public Pcr reference( String reference) {
    this.reference = reference;
    return this;
  }

  /**
   * The reference
   * @return reference
   */
  
 @Pattern(regexp="[a-zA-Z0-9- &#\\?:_/,\\.']{0,12}") @Size(max=12)
  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getReference() {
    return reference;
  }


  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReference( String reference) {
    this.reference = reference;
  }


  /**
   * Return true if this pcr object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pcr pcr = (Pcr) o;
    return Objects.equals(this.particulars, pcr.particulars) &&
        Objects.equals(this.code, pcr.code) &&
        Objects.equals(this.reference, pcr.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(particulars, code, reference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pcr {\n");
    sb.append("    particulars: ").append(toIndentedString(particulars)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `particulars` to the URL query string
    if (getParticulars() != null) {
      joiner.add(String.format(Locale.ROOT, "%sparticulars%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getParticulars()))));
    }

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format(Locale.ROOT, "%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    // add `reference` to the URL query string
    if (getReference() != null) {
      joiner.add(String.format(Locale.ROOT, "%sreference%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReference()))));
    }

    return joiner.toString();
  }
}

