/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import nz.co.blink.debit.dto.v1.Amount;
import nz.co.blink.debit.dto.v1.AuthFlow;
import nz.co.blink.debit.dto.v1.Pcr;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The model for a quick payment, relating to a single consent and a one-off payment.
 */
@JsonPropertyOrder({
  QuickPaymentRequest.JSON_PROPERTY_TYPE,
  QuickPaymentRequest.JSON_PROPERTY_FLOW,
  QuickPaymentRequest.JSON_PROPERTY_PCR,
  QuickPaymentRequest.JSON_PROPERTY_AMOUNT,
  QuickPaymentRequest.JSON_PROPERTY_HASHED_CUSTOMER_IDENTIFIER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class QuickPaymentRequest {
  /**
   * Whether the consent is single or enduring.
   */
  public enum TypeEnum {
    SINGLE(String.valueOf("single")),
    
    ENDURING(String.valueOf("enduring"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  
  private TypeEnum type;

  public static final String JSON_PROPERTY_FLOW = "flow";
  
  private AuthFlow flow;

  public static final String JSON_PROPERTY_PCR = "pcr";
  
  private Pcr pcr;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  
  private Amount amount;

  public static final String JSON_PROPERTY_HASHED_CUSTOMER_IDENTIFIER = "hashed_customer_identifier";
  
  private String hashedCustomerIdentifier;

  public QuickPaymentRequest() { 
  }

  @JsonCreator
  public QuickPaymentRequest(
    @JsonProperty(JSON_PROPERTY_TYPE) TypeEnum type
  ) {
  this();
    this.type = type;
  }

  /**
   * Whether the consent is single or enduring.
   * @return type
   */
  

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TypeEnum getType() {
    return type;
  }




  public QuickPaymentRequest flow( AuthFlow flow) {
    this.flow = flow;
    return this;
  }

  /**
   * Get flow
   * @return flow
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_FLOW, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AuthFlow getFlow() {
    return flow;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOW, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlow( AuthFlow flow) {
    this.flow = flow;
  }


  public QuickPaymentRequest pcr( Pcr pcr) {
    this.pcr = pcr;
    return this;
  }

  /**
   * Get pcr
   * @return pcr
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_PCR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Pcr getPcr() {
    return pcr;
  }


  @JsonProperty(value = JSON_PROPERTY_PCR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPcr( Pcr pcr) {
    this.pcr = pcr;
  }


  public QuickPaymentRequest amount( Amount amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Amount getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount( Amount amount) {
    this.amount = amount;
  }


  public QuickPaymentRequest hashedCustomerIdentifier( String hashedCustomerIdentifier) {
    this.hashedCustomerIdentifier = hashedCustomerIdentifier;
    return this;
  }

  /**
   * The hashed unique ID of the customer e.g. customer internal ID. SHA-256 is recommended.
   * @return hashedCustomerIdentifier
   */
  

  @JsonProperty(value = JSON_PROPERTY_HASHED_CUSTOMER_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHashedCustomerIdentifier() {
    return hashedCustomerIdentifier;
  }


  @JsonProperty(value = JSON_PROPERTY_HASHED_CUSTOMER_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHashedCustomerIdentifier( String hashedCustomerIdentifier) {
    this.hashedCustomerIdentifier = hashedCustomerIdentifier;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public QuickPaymentRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  /**
   * Return true if this quick-payment-request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuickPaymentRequest quickPaymentRequest = (QuickPaymentRequest) o;
    return Objects.equals(this.type, quickPaymentRequest.type) &&
        Objects.equals(this.flow, quickPaymentRequest.flow) &&
        Objects.equals(this.pcr, quickPaymentRequest.pcr) &&
        Objects.equals(this.amount, quickPaymentRequest.amount) &&
        Objects.equals(this.hashedCustomerIdentifier, quickPaymentRequest.hashedCustomerIdentifier)&&
        Objects.equals(this.additionalProperties, quickPaymentRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, flow, pcr, amount, hashedCustomerIdentifier, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuickPaymentRequest {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    flow: ").append(toIndentedString(flow)).append("\n");
    sb.append("    pcr: ").append(toIndentedString(pcr)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    hashedCustomerIdentifier: ").append(toIndentedString(hashedCustomerIdentifier)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `flow` to the URL query string
    if (getFlow() != null) {
      joiner.add(getFlow().toUrlQueryString(prefix + "flow" + suffix));
    }

    // add `pcr` to the URL query string
    if (getPcr() != null) {
      joiner.add(getPcr().toUrlQueryString(prefix + "pcr" + suffix));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(getAmount().toUrlQueryString(prefix + "amount" + suffix));
    }

    // add `hashed_customer_identifier` to the URL query string
    if (getHashedCustomerIdentifier() != null) {
      joiner.add(String.format(Locale.ROOT, "%shashed_customer_identifier%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHashedCustomerIdentifier()))));
    }

    return joiner.toString();
  }
}

