/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import nz.co.blink.debit.dto.v1.Consent;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The model for quick payment response.
 */
@JsonPropertyOrder({
  QuickPaymentResponse.JSON_PROPERTY_QUICK_PAYMENT_ID,
  QuickPaymentResponse.JSON_PROPERTY_CONSENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class QuickPaymentResponse {
  public static final String JSON_PROPERTY_QUICK_PAYMENT_ID = "quick_payment_id";
  
  private UUID quickPaymentId;

  public static final String JSON_PROPERTY_CONSENT = "consent";
  
  private Consent consent;

  public QuickPaymentResponse() { 
  }

  public QuickPaymentResponse quickPaymentId( UUID quickPaymentId) {
    this.quickPaymentId = quickPaymentId;
    return this;
  }

  /**
   * The quick payment ID.
   * @return quickPaymentId
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_QUICK_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getQuickPaymentId() {
    return quickPaymentId;
  }


  @JsonProperty(value = JSON_PROPERTY_QUICK_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuickPaymentId( UUID quickPaymentId) {
    this.quickPaymentId = quickPaymentId;
  }


  public QuickPaymentResponse consent( Consent consent) {
    this.consent = consent;
    return this;
  }

  /**
   * Get consent
   * @return consent
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CONSENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Consent getConsent() {
    return consent;
  }


  @JsonProperty(value = JSON_PROPERTY_CONSENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConsent( Consent consent) {
    this.consent = consent;
  }


  /**
   * Return true if this quick-payment-response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuickPaymentResponse quickPaymentResponse = (QuickPaymentResponse) o;
    return Objects.equals(this.quickPaymentId, quickPaymentResponse.quickPaymentId) &&
        Objects.equals(this.consent, quickPaymentResponse.consent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quickPaymentId, consent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuickPaymentResponse {\n");
    sb.append("    quickPaymentId: ").append(toIndentedString(quickPaymentId)).append("\n");
    sb.append("    consent: ").append(toIndentedString(consent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `quick_payment_id` to the URL query string
    if (getQuickPaymentId() != null) {
      joiner.add(String.format(Locale.ROOT, "%squick_payment_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuickPaymentId()))));
    }

    // add `consent` to the URL query string
    if (getConsent() != null) {
      joiner.add(getConsent().toUrlQueryString(prefix + "consent" + suffix));
    }

    return joiner.toString();
  }
}

