/*
 * Blink Debit (PayNow and AutoPay) Payments API
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: sysadmin@blinkpay.co.nz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package nz.co.blink.debit.dto.v1;
import nz.co.blink.debit.dto.ApiClient;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import nz.co.blink.debit.dto.v1.RefundDetail;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


/**
 * The model for a refund.
 */
@JsonPropertyOrder({
  Refund.JSON_PROPERTY_REFUND_ID,
  Refund.JSON_PROPERTY_STATUS,
  Refund.JSON_PROPERTY_CREATION_TIMESTAMP,
  Refund.JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP,
  Refund.JSON_PROPERTY_ACCOUNT_NUMBER,
  Refund.JSON_PROPERTY_DETAIL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Refund {
  public static final String JSON_PROPERTY_REFUND_ID = "refund_id";
  
  private UUID refundId;

  /**
   * The refund status
   */
  public enum StatusEnum {
    FAILED(String.valueOf("failed")),
    
    PROCESSING(String.valueOf("processing")),
    
    COMPLETED(String.valueOf("completed"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  
  private StatusEnum status;

  public static final String JSON_PROPERTY_CREATION_TIMESTAMP = "creation_timestamp";
  
  private OffsetDateTime creationTimestamp;

  public static final String JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP = "status_updated_timestamp";
  
  private OffsetDateTime statusUpdatedTimestamp;

  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "account_number";
  
  private String accountNumber;

  public static final String JSON_PROPERTY_DETAIL = "detail";
  
  private RefundDetail detail;

  public Refund() { 
  }

  public Refund refundId( UUID refundId) {
    this.refundId = refundId;
    return this;
  }

  /**
   * The refund ID.
   * @return refundId
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_REFUND_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getRefundId() {
    return refundId;
  }


  @JsonProperty(value = JSON_PROPERTY_REFUND_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRefundId( UUID refundId) {
    this.refundId = refundId;
  }


  public Refund status( StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * The refund status
   * @return status
   */
  
  @NotNull

  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus( StatusEnum status) {
    this.status = status;
  }


  public Refund creationTimestamp( OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

  /**
   * The time that the refund was created.
   * @return creationTimestamp
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_CREATION_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreationTimestamp() {
    return creationTimestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreationTimestamp( OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }


  public Refund statusUpdatedTimestamp( OffsetDateTime statusUpdatedTimestamp) {
    this.statusUpdatedTimestamp = statusUpdatedTimestamp;
    return this;
  }

  /**
   * The time that the status was last updated.
   * @return statusUpdatedTimestamp
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getStatusUpdatedTimestamp() {
    return statusUpdatedTimestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_UPDATED_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatusUpdatedTimestamp( OffsetDateTime statusUpdatedTimestamp) {
    this.statusUpdatedTimestamp = statusUpdatedTimestamp;
  }


  public Refund accountNumber( String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

  /**
   * The customer account number used or to be used for the refund.
   * @return accountNumber
   */
  
  @NotNull
 @Pattern(regexp="^\\d{2}-\\d{4}-\\d{7}-\\d{2}$")
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccountNumber() {
    return accountNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountNumber( String accountNumber) {
    this.accountNumber = accountNumber;
  }


  public Refund detail( RefundDetail detail) {
    this.detail = detail;
    return this;
  }

  /**
   * Get detail
   * @return detail
   */
  
  @NotNull
  @Valid

  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RefundDetail getDetail() {
    return detail;
  }


  @JsonProperty(value = JSON_PROPERTY_DETAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDetail( RefundDetail detail) {
    this.detail = detail;
  }


  /**
   * Return true if this refund object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Refund refund = (Refund) o;
    return Objects.equals(this.refundId, refund.refundId) &&
        Objects.equals(this.status, refund.status) &&
        Objects.equals(this.creationTimestamp, refund.creationTimestamp) &&
        Objects.equals(this.statusUpdatedTimestamp, refund.statusUpdatedTimestamp) &&
        Objects.equals(this.accountNumber, refund.accountNumber) &&
        Objects.equals(this.detail, refund.detail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(refundId, status, creationTimestamp, statusUpdatedTimestamp, accountNumber, detail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Refund {\n");
    sb.append("    refundId: ").append(toIndentedString(refundId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
    sb.append("    statusUpdatedTimestamp: ").append(toIndentedString(statusUpdatedTimestamp)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `refund_id` to the URL query string
    if (getRefundId() != null) {
      joiner.add(String.format(Locale.ROOT, "%srefund_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRefundId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `creation_timestamp` to the URL query string
    if (getCreationTimestamp() != null) {
      joiner.add(String.format(Locale.ROOT, "%screation_timestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreationTimestamp()))));
    }

    // add `status_updated_timestamp` to the URL query string
    if (getStatusUpdatedTimestamp() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstatus_updated_timestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusUpdatedTimestamp()))));
    }

    // add `account_number` to the URL query string
    if (getAccountNumber() != null) {
      joiner.add(String.format(Locale.ROOT, "%saccount_number%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccountNumber()))));
    }

    // add `detail` to the URL query string
    // NOTE: Commented out due to hand-written RefundDetail not having toUrlQueryString method
    // if (getDetail() != null) {
    //   joiner.add(getDetail().toUrlQueryString(prefix + "detail" + suffix));
    // }

    return joiner.toString();
  }
}

