/**
 * Copyright (c) 2022 BlinkPay
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package nz.co.blink.debit.client.v1;

import io.github.resilience4j.reactor.retry.RetryOperator;
import io.github.resilience4j.retry.Retry;
import lombok.extern.slf4j.Slf4j;
import nz.co.blink.debit.config.BlinkPayProperties;
import nz.co.blink.debit.dto.v1.Payment;
import nz.co.blink.debit.dto.v1.PaymentRequest;
import nz.co.blink.debit.dto.v1.PaymentResponse;
import nz.co.blink.debit.enums.BlinkDebitConstant;
import nz.co.blink.debit.exception.BlinkInvalidValueException;
import nz.co.blink.debit.exception.BlinkServiceException;
import nz.co.blink.debit.helpers.AccessTokenHandler;
import nz.co.blink.debit.helpers.RequestHandler;
import nz.co.blink.debit.helpers.ResponseHandler;
import nz.co.blink.debit.service.ValidationService;
import org.apache.commons.collections4.MapUtils;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.client.reactive.ReactorClientHttpConnector;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import static nz.co.blink.debit.enums.BlinkDebitConstant.CUSTOMER_IP;
import static nz.co.blink.debit.enums.BlinkDebitConstant.CUSTOMER_USER_AGENT;
import static nz.co.blink.debit.enums.BlinkDebitConstant.IDEMPOTENCY_KEY;
import static nz.co.blink.debit.enums.BlinkDebitConstant.PAYMENTS_PATH;
import static nz.co.blink.debit.enums.BlinkDebitConstant.REQUEST_ID;

/**
 * The client for payments.
 */
@Component
@Slf4j
public class PaymentsApiClient {

    private final ReactorClientHttpConnector connector;

    private final String debitUrl;

    private final AccessTokenHandler accessTokenHandler;

    private final ValidationService validationService;

    private final Retry retry;

    private WebClient.Builder webClientBuilder;

    /**
     * Default constructor.
     *
     * @param connector          the {@link ReactorClientHttpConnector}
     * @param properties         the {@link BlinkPayProperties}
     * @param accessTokenHandler the {@link AccessTokenHandler}
     * @param validationService  the {@link ValidationService}
     * @param retry              the {@link Retry} instance
     */
    @Autowired
    public PaymentsApiClient(@Qualifier("blinkDebitClientHttpConnector") ReactorClientHttpConnector connector,
                             BlinkPayProperties properties, AccessTokenHandler accessTokenHandler,
                             ValidationService validationService, Retry retry) {
        this.connector = connector;
        debitUrl = properties.getDebit().getUrl();
        this.accessTokenHandler = accessTokenHandler;
        this.validationService = validationService;
        this.retry = retry;
    }

    /**
     * Creates a payment.
     *
     * @param request the {@link PaymentRequest}
     * @return the {@link PaymentResponse} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<PaymentResponse> createPayment(PaymentRequest request) throws BlinkServiceException {
        return createPayment(request, new HashMap<>());
    }

    /**
     * Creates a payment.
     *
     * @param request   the {@link PaymentRequest}
     * @param requestId the optional request ID. If provided, it overrides the interaction ID generated by Blink Debit.
     * @return the {@link PaymentResponse} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<PaymentResponse> createPayment(PaymentRequest request, final String requestId)
            throws BlinkServiceException {
        Map<String, String> requestHeaders = new HashMap<>();
        requestHeaders.put(REQUEST_ID.getValue(), requestId);

        return createPayment(request, requestHeaders);
    }

    /**
     * Creates a payment.
     *
     * @param request        the {@link PaymentRequest}
     * @param requestHeaders the {@link Map} of optional request headers
     * @return the {@link PaymentResponse} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<PaymentResponse> createPayment(PaymentRequest request, Map<String, String> requestHeaders)
            throws BlinkServiceException {
        if (request == null) {
            throw new BlinkInvalidValueException("Payment request must not be null");
        }

        if (request.getConsentId() == null) {
            throw new BlinkInvalidValueException("Consent ID must not be null");
        }

        if (request.getPcr() != null) {
            String particulars = StringUtils.trim(request.getPcr().getParticulars());
            request.getPcr().setParticulars(particulars);
        }

        if (request.getAmount() != null) {
            String total = StringUtils.trim(request.getAmount().getTotal());
            request.getAmount().setTotal(total);
        }

        validationService.validateRequest("payment", request);

        return createPaymentMono(request, requestHeaders);
    }

    /**
     * Retrieves an existing payment by ID.
     *
     * @param paymentId the payment ID
     * @return the {@link Payment} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<Payment> getPayment(UUID paymentId) throws BlinkServiceException {
        return getPayment(paymentId, new HashMap<>());
    }

    /**
     * Retrieves an existing payment by ID.
     *
     * @param paymentId the payment ID
     * @param requestId the optional request ID. If provided, it overrides the interaction ID generated by Blink Debit.
     * @return the {@link Payment} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<Payment> getPayment(UUID paymentId, final String requestId) throws BlinkServiceException {
        Map<String, String> requestHeaders = new HashMap<>();
        requestHeaders.put(REQUEST_ID.getValue(), requestId);

        return getPayment(paymentId, requestHeaders);
    }

    /**
     * Retrieves an existing payment by ID.
     *
     * @param paymentId      the payment ID
     * @param requestHeaders the {@link Map} of optional request headers
     * @return the {@link Payment} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<Payment> getPayment(UUID paymentId, Map<String, String> requestHeaders) throws BlinkServiceException {
        if (paymentId == null) {
            throw new BlinkInvalidValueException("Payment ID must not be null");
        }

        String requestId = MapUtils.getString(requestHeaders, REQUEST_ID.getValue(), UUID.randomUUID().toString());
        String customerIp = MapUtils.getString(requestHeaders, CUSTOMER_IP.getValue(), (String) null);
        String customerUserAgent = MapUtils.getString(requestHeaders, CUSTOMER_USER_AGENT.getValue(), (String) null);

        return getWebClientBuilder(requestId)
                .filter((clientRequest, exchangeFunction) -> RequestHandler.logRequest(null, clientRequest,
                        exchangeFunction))
                .build()
                .get()
                .uri(uriBuilder -> uriBuilder
                        .path(PAYMENTS_PATH.getValue() + "/{paymentId}")
                        .build(paymentId))
                .accept(MediaType.APPLICATION_JSON)
                .headers(httpHeaders -> {
                    httpHeaders.add(REQUEST_ID.getValue(), requestId);
                    httpHeaders.add(CUSTOMER_IP.getValue(), customerIp);
                    httpHeaders.add(CUSTOMER_USER_AGENT.getValue(), customerUserAgent);
                })
                .exchangeToMono(ResponseHandler.handleResponseMono(Payment.class))
                .transformDeferred(RetryOperator.of(retry));
    }

    private Mono<PaymentResponse> createPaymentMono(PaymentRequest request, Map<String, String> requestHeaders)
            throws BlinkServiceException {
        String requestId = MapUtils.getString(requestHeaders, REQUEST_ID.getValue(), UUID.randomUUID().toString());
        String customerIp = MapUtils.getString(requestHeaders, CUSTOMER_IP.getValue(), (String) null);
        String customerUserAgent = MapUtils.getString(requestHeaders, CUSTOMER_USER_AGENT.getValue(), (String) null);
        String idempotencyKey = UUID.randomUUID().toString();

        return getWebClientBuilder(requestId)
                .filter((clientRequest, exchangeFunction) -> RequestHandler.logRequest(request, clientRequest,
                        exchangeFunction))
                .build()
                .post()
                .uri(PAYMENTS_PATH.getValue())
                .accept(MediaType.APPLICATION_JSON)
                .contentType(MediaType.APPLICATION_JSON)
                .headers(httpHeaders -> {
                    httpHeaders.add(REQUEST_ID.getValue(), requestId);
                    httpHeaders.add(IDEMPOTENCY_KEY.getValue(), idempotencyKey);
                    httpHeaders.add(CUSTOMER_IP.getValue(), customerIp);
                    httpHeaders.add(CUSTOMER_USER_AGENT.getValue(), customerUserAgent);
                })
                .bodyValue(request)
                .exchangeToMono(ResponseHandler.handleResponseMono(PaymentResponse.class))
                .transformDeferred(RetryOperator.of(retry));
    }

    private WebClient.Builder getWebClientBuilder(String requestId) throws BlinkServiceException {
        if (webClientBuilder == null) {
            webClientBuilder = WebClient.builder()
                    .clientConnector(connector)
                    .defaultHeader(HttpHeaders.USER_AGENT, BlinkDebitConstant.USER_AGENT_VALUE.getValue())
                    .baseUrl(debitUrl);
        }

        // Clone builder and add per-request filter
        return webClientBuilder.clone()
                .filter(accessTokenHandler.setAccessToken(requestId));
    }
}
