/**
 * Copyright (c) 2022 BlinkPay
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package nz.co.blink.debit.client.v1;

import io.github.resilience4j.reactor.retry.RetryOperator;
import io.github.resilience4j.retry.Retry;
import lombok.extern.slf4j.Slf4j;
import nz.co.blink.debit.config.BlinkPayProperties;
import nz.co.blink.debit.dto.v1.FullRefundRequest;
import nz.co.blink.debit.dto.v1.PartialRefundRequest;
import nz.co.blink.debit.dto.v1.Payment;
import nz.co.blink.debit.dto.v1.Pcr;
import nz.co.blink.debit.dto.v1.Refund;
import nz.co.blink.debit.dto.v1.RefundDetail;
import nz.co.blink.debit.dto.v1.RefundResponse;
import nz.co.blink.debit.enums.BlinkDebitConstant;
import nz.co.blink.debit.exception.BlinkInvalidValueException;
import nz.co.blink.debit.exception.BlinkServiceException;
import nz.co.blink.debit.helpers.AccessTokenHandler;
import nz.co.blink.debit.helpers.RequestHandler;
import nz.co.blink.debit.helpers.ResponseHandler;
import nz.co.blink.debit.service.ValidationService;
import org.apache.commons.collections4.MapUtils;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.client.reactive.ReactorClientHttpConnector;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import static nz.co.blink.debit.enums.BlinkDebitConstant.CUSTOMER_IP;
import static nz.co.blink.debit.enums.BlinkDebitConstant.CUSTOMER_USER_AGENT;
import static nz.co.blink.debit.enums.BlinkDebitConstant.REFUNDS_PATH;
import static nz.co.blink.debit.enums.BlinkDebitConstant.REQUEST_ID;

/**
 * The client for refunds.
 */
@Component
@Slf4j
public class RefundsApiClient {

    private final ReactorClientHttpConnector connector;

    private final String debitUrl;

    private final AccessTokenHandler accessTokenHandler;

    private final ValidationService validationService;

    private final Retry retry;

    private WebClient.Builder webClientBuilder;

    /**
     * Default constructor.
     *
     * @param connector          the {@link ReactorClientHttpConnector}
     * @param properties         the {@link BlinkPayProperties}
     * @param accessTokenHandler the {@link AccessTokenHandler}
     * @param validationService  the {@link ValidationService}
     * @param retry              the {@link Retry} instance
     */
    @Autowired
    public RefundsApiClient(@Qualifier("blinkDebitClientHttpConnector") ReactorClientHttpConnector connector,
                            BlinkPayProperties properties, AccessTokenHandler accessTokenHandler,
                            ValidationService validationService, Retry retry) {
        this.connector = connector;
        debitUrl = properties.getDebit().getUrl();
        this.accessTokenHandler = accessTokenHandler;
        this.validationService = validationService;
        this.retry = retry;
    }

    /**
     * Creates a refund.
     *
     * @param request the {@link PartialRefundRequest}
     * @return the {@link RefundResponse} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<RefundResponse> createRefund(RefundDetail request) throws BlinkServiceException {
        return createRefund(request, new HashMap<>());
    }

    /**
     * Creates a refund.
     *
     * @param request   the {@link RefundDetail}
     * @param requestId the optional request ID. If provided, it overrides the interaction ID generated by Blink Debit.
     * @return the {@link RefundResponse} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<RefundResponse> createRefund(RefundDetail request, final String requestId)
            throws BlinkServiceException {
        Map<String, String> requestHeaders = new HashMap<>();
        requestHeaders.put(REQUEST_ID.getValue(), requestId);

        return createRefund(request, requestHeaders);
    }

    /**
     * Creates a refund.
     *
     * @param request        the {@link RefundDetail}
     * @param requestHeaders the {@link Map} of optional request headers
     * @return the {@link RefundResponse} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<RefundResponse> createRefund(RefundDetail request, Map<String, String> requestHeaders)
            throws BlinkServiceException {
        if (request == null) {
            throw new BlinkInvalidValueException("Refund request must not be null");
        }

        if (request.getPaymentId() == null) {
            throw new BlinkInvalidValueException("Payment ID must not be null");
        }

        if (request instanceof PartialRefundRequest partialRefundRequest) {
            validatePcr(partialRefundRequest.getPcr());

            if (partialRefundRequest.getAmount() == null) {
                throw new BlinkInvalidValueException("Amount must not be null");
            }

            if (partialRefundRequest.getAmount().getCurrency() == null) {
                throw new BlinkInvalidValueException("Currency must not be null");
            }
        } else if (request instanceof FullRefundRequest fullRefundRequest) {
            validatePcr(fullRefundRequest.getPcr());
        }

        validationService.validateRequest("refund", request);

        return createRefundMono(request, requestHeaders);
    }

    /**
     * Retrieves an existing refund by ID.
     *
     * @param refundId the refund ID
     * @return the {@link Payment} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<Refund> getRefund(UUID refundId) throws BlinkServiceException {
        return getRefund(refundId, new HashMap<>());
    }

    /**
     * Retrieves an existing refund by ID.
     *
     * @param refundId  the refund ID
     * @param requestId the optional request ID. If provided, it overrides the interaction ID generated by Blink Debit.
     * @return the {@link Payment} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<Refund> getRefund(UUID refundId, final String requestId) throws BlinkServiceException {
        Map<String, String> requestHeaders = new HashMap<>();
        requestHeaders.put(REQUEST_ID.getValue(), requestId);

        return getRefund(refundId, requestHeaders);
    }

    /**
     * Retrieves an existing refund by ID.
     *
     * @param refundId       the refund ID
     * @param requestHeaders the {@link Map} of optional request headers
     * @return the {@link Payment} {@link Mono}
     * @throws BlinkServiceException thrown when an exception occurs
     */
    public Mono<Refund> getRefund(UUID refundId, Map<String, String> requestHeaders) throws BlinkServiceException {
        if (refundId == null) {
            throw new BlinkInvalidValueException("Refund ID must not be null");
        }

        String requestId = MapUtils.getString(requestHeaders, REQUEST_ID.getValue(), UUID.randomUUID().toString());
        String customerIp = MapUtils.getString(requestHeaders, CUSTOMER_IP.getValue(), null);
        String customerUserAgent = MapUtils.getString(requestHeaders, CUSTOMER_USER_AGENT.getValue(), null);

        return getWebClientBuilder(requestId)
                .filter((clientRequest, exchangeFunction) -> RequestHandler.logRequest(null, clientRequest,
                        exchangeFunction))
                .build()
                .get()
                .uri(uriBuilder -> uriBuilder
                        .path(REFUNDS_PATH.getValue() + "/{refundId}")
                        .build(refundId))
                .accept(MediaType.APPLICATION_JSON)
                .headers(httpHeaders -> {
                    httpHeaders.add(REQUEST_ID.getValue(), requestId);
                    httpHeaders.add(CUSTOMER_IP.getValue(), customerIp);
                    httpHeaders.add(CUSTOMER_USER_AGENT.getValue(), customerUserAgent);
                })
                .exchangeToMono(ResponseHandler.handleResponseMono(Refund.class));
    }

    private Mono<RefundResponse> createRefundMono(RefundDetail request, Map<String, String> requestHeaders)
            throws BlinkServiceException {
        String requestId = MapUtils.getString(requestHeaders, REQUEST_ID.getValue(), UUID.randomUUID().toString());
        String customerIp = MapUtils.getString(requestHeaders, CUSTOMER_IP.getValue(), null);
        String customerUserAgent = MapUtils.getString(requestHeaders, CUSTOMER_USER_AGENT.getValue(), null);

        return getWebClientBuilder(requestId)
                .filter((clientRequest, exchangeFunction) -> RequestHandler.logRequest(null, clientRequest,
                        exchangeFunction))
                .build()
                .post()
                .uri(REFUNDS_PATH.getValue())
                .accept(MediaType.APPLICATION_JSON)
                .contentType(MediaType.APPLICATION_JSON)
                .headers(httpHeaders -> {
                    httpHeaders.add(REQUEST_ID.getValue(), requestId);
                    httpHeaders.add(CUSTOMER_IP.getValue(), customerIp);
                    httpHeaders.add(CUSTOMER_USER_AGENT.getValue(), customerUserAgent);
                })
                .bodyValue(request)
                .exchangeToMono(ResponseHandler.handleResponseMono(RefundResponse.class))
                .transformDeferred(RetryOperator.of(retry));
    }

    private WebClient.Builder getWebClientBuilder(String requestId) throws BlinkServiceException {
        if (webClientBuilder != null) {
            return webClientBuilder;
        }

        return WebClient.builder()
                .clientConnector(connector)
                .defaultHeader(HttpHeaders.USER_AGENT, BlinkDebitConstant.USER_AGENT_VALUE.getValue())
                .baseUrl(debitUrl)
                .filter(accessTokenHandler.setAccessToken(requestId));
    }

    private static void validatePcr(Pcr pcr) throws BlinkServiceException {
        if (pcr == null) {
            throw new BlinkInvalidValueException("PCR must not be null");
        }

        if (StringUtils.isBlank(pcr.getParticulars())) {
            throw new BlinkInvalidValueException("Particulars must have at least 1 character");
        }

        if (StringUtils.length(pcr.getParticulars()) > 12
            || StringUtils.length(pcr.getCode()) > 12
            || StringUtils.length(pcr.getReference()) > 12) {
            throw new BlinkInvalidValueException("PCR must not exceed 12 characters");
        }
    }
}
