blinkpay:
  debit:
    url: http://localhost:8080
  max:
    connections: 50
    idle:
      time: PT20S
    life:
      time: PT60S
  pending:
    acquire:
      timeout: PT10S
  eviction:
    interval: PT60S
  client:
    id: ${BLINKPAY_CLIENT_ID}
    secret: ${BLINKPAY_CLIENT_SECRET}
  access:
    token: ${BLINKPAY_ACCESS_TOKEN}