package nz.co.blink.debit.client.v1;

import nz.co.blink.debit.dto.v1.SingleConsentRequest;
import nz.co.blink.debit.exception.BlinkInvalidValueException;
import nz.co.blink.debit.helpers.HttpClientHelper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThatThrownBy;

class SingleConsentsApiClientTest {

    private SingleConsentsApiClient client;

    @BeforeEach
    void setUp() {
        // Create client with null HttpClientHelper - we're only testing validation
        client = new SingleConsentsApiClient(null);
    }

    // ===== createSingleConsent Validation Tests =====

    @Test
    void testCreateSingleConsentWithNullRequest() {
        assertThatThrownBy(() -> client.createSingleConsent(null))
                .isInstanceOf(BlinkInvalidValueException.class)
                .hasMessageContaining("Single consent request must not be null");
    }

    @Test
    void testCreateSingleConsentWithNullRequestAndCustomRequestId() {
        assertThatThrownBy(() -> client.createSingleConsent(null, "custom-request-id"))
                .isInstanceOf(BlinkInvalidValueException.class)
                .hasMessageContaining("Single consent request must not be null");
    }

    @Test
    void testCreateSingleConsentWithValidRequestThrowsNullPointerDueToNullHttpHelper() {
        // This test verifies validation passes and execution reaches HttpClientHelper
        SingleConsentRequest request = new SingleConsentRequest();

        assertThatThrownBy(() -> client.createSingleConsent(request))
                .isInstanceOf(NullPointerException.class); // HttpClientHelper is null
    }

    // ===== getConsent Validation Tests =====

    @Test
    void testGetConsentWithNullId() {
        assertThatThrownBy(() -> client.getConsent(null))
                .isInstanceOf(BlinkInvalidValueException.class)
                .hasMessageContaining("Consent ID must not be null");
    }

    @Test
    void testGetConsentWithNullIdAndCustomRequestId() {
        assertThatThrownBy(() -> client.getConsent(null, "custom-request-id"))
                .isInstanceOf(BlinkInvalidValueException.class)
                .hasMessageContaining("Consent ID must not be null");
    }

    @Test
    void testGetConsentWithValidIdThrowsNullPointerDueToNullHttpHelper() {
        UUID validId = UUID.randomUUID();

        assertThatThrownBy(() -> client.getConsent(validId))
                .isInstanceOf(NullPointerException.class); // HttpClientHelper is null
    }

    // ===== revokeConsent Validation Tests =====

    @Test
    void testRevokeConsentWithNullId() {
        assertThatThrownBy(() -> client.revokeConsent(null))
                .isInstanceOf(BlinkInvalidValueException.class)
                .hasMessageContaining("Consent ID must not be null");
    }

    @Test
    void testRevokeConsentWithNullIdAndCustomRequestId() {
        assertThatThrownBy(() -> client.revokeConsent(null, "custom-request-id"))
                .isInstanceOf(BlinkInvalidValueException.class)
                .hasMessageContaining("Consent ID must not be null");
    }

    @Test
    void testRevokeConsentWithValidIdThrowsNullPointerDueToNullHttpHelper() {
        UUID validId = UUID.randomUUID();

        assertThatThrownBy(() -> client.revokeConsent(validId))
                .isInstanceOf(NullPointerException.class); // HttpClientHelper is null
    }

    // ===== Request ID Handling Tests =====

    @Test
    void testAutoGeneratedRequestIdStillValidatesInput() {
        // Even with auto-generated request ID, validation should happen first
        assertThatThrownBy(() -> client.createSingleConsent(null))
                .isInstanceOf(BlinkInvalidValueException.class)
                .hasMessageContaining("Single consent request must not be null");

        assertThatThrownBy(() -> client.getConsent(null))
                .isInstanceOf(BlinkInvalidValueException.class)
                .hasMessageContaining("Consent ID must not be null");

        assertThatThrownBy(() -> client.revokeConsent(null))
                .isInstanceOf(BlinkInvalidValueException.class)
                .hasMessageContaining("Consent ID must not be null");
    }
}
