name: 64-bit Corretto 8 CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up 64-bit Corretto 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          architecture: x64
          cache: maven
          
      - name: Run unit tests
        run: SPRING_PROFILES_ACTIVE=test mvn -Dgroups=unit test
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Run component tests
        run: mvn -Dgroups=component test
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BLINKPAY_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          BLINKPAY_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          
      - name: Run integration tests
        run: mvn -Dgroups=integration test
        env:
          BLINKPAY_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          BLINKPAY_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        
      - name: Package
        run: mvn clean package -DskipTests=true

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif