name: 64-bit Corretto 8 CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up 64-bit Corretto 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          architecture: x64
          cache: maven
          
      - name: Run unit tests
        run: SPRING_PROFILES_ACTIVE=test mvn -Dgroups=unit test
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Run component tests
        run: SPRING_PROFILES_ACTIVE=test mvn -Dgroups=component test
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BLINKPAY_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          BLINKPAY_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          
      - name: Run integration tests
        run: mvn -Dgroups=integration test
        env:
          BLINKPAY_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          BLINKPAY_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BLINKPAY_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
      - name: Package
        run: mvn clean package -DskipTests=true

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Sonar to inspect code
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args:
            -Dsonar.projectKey=blink-debit-api-client-java
            -Dsonar.organization=blinkpay
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.junit.reportPaths=target/surefire-reports
            -Dsonar.coverage.plugin=jacoco
            -Dsonar.coverage.jacoco.xmlReportPaths=target/coverage-reports/jacoco-ut/jacoco.xml
#            -Dsonar.inclusions=src/main/**
#            -Dsonar.test.exclusions=src/test/**,src/componentTest/**,src/integrationTest/**

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Set up 64-bit Corretto 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          architecture: x64
          cache: maven

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is the default env for the password

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          java-version: '8'
          distribution: 'corretto'
          architecture: x64
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.OSSRH_GPG_PASSPHRASE }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Publish to Apache Maven Central
        run: mvn deploy -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}